// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/alert.proto

package containariumv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertRule represents an alerting rule evaluated by vmalert
type AlertRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name for the alert rule
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// PromQL expression to evaluate
	Expr string `protobuf:"bytes,3,opt,name=expr,proto3" json:"expr,omitempty"`
	// Duration the expression must be true before firing (e.g. "5m")
	Duration string `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	// Severity level: "critical", "warning", or "info"
	Severity string `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	// Human-readable description of what this alert means
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Additional labels attached to the alert
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Annotations (e.g. summary, runbook_url)
	Annotations map[string]string `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether the rule is active
	Enabled bool `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Unix timestamp (seconds) when the rule was created
	CreatedAt int64 `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unix timestamp (seconds) when the rule was last updated
	UpdatedAt     int64 `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRule) Reset() {
	*x = AlertRule{}
	mi := &file_containarium_v1_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRule) ProtoMessage() {}

func (x *AlertRule) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRule.ProtoReflect.Descriptor instead.
func (*AlertRule) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{0}
}

func (x *AlertRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertRule) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *AlertRule) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *AlertRule) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlertRule) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AlertRule) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *AlertRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlertRule) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AlertRule) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CreateAlertRuleRequest creates a new alert rule
type CreateAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expr          string                 `protobuf:"bytes,2,opt,name=expr,proto3" json:"expr,omitempty"`
	Duration      string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleRequest) Reset() {
	*x = CreateAlertRuleRequest{}
	mi := &file_containarium_v1_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleRequest) ProtoMessage() {}

func (x *CreateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlertRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateAlertRuleRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *CreateAlertRuleRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// CreateAlertRuleResponse returns the created alert rule
type CreateAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleResponse) Reset() {
	*x = CreateAlertRuleResponse{}
	mi := &file_containarium_v1_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleResponse) ProtoMessage() {}

func (x *CreateAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAlertRuleResponse) GetRule() *AlertRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// GetAlertRuleRequest gets a single alert rule by ID
type GetAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRuleRequest) Reset() {
	*x = GetAlertRuleRequest{}
	mi := &file_containarium_v1_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRuleRequest) ProtoMessage() {}

func (x *GetAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlertRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetAlertRuleResponse returns a single alert rule
type GetAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRuleResponse) Reset() {
	*x = GetAlertRuleResponse{}
	mi := &file_containarium_v1_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRuleResponse) ProtoMessage() {}

func (x *GetAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*GetAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlertRuleResponse) GetRule() *AlertRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// ListAlertRulesRequest lists all alert rules
type ListAlertRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRulesRequest) Reset() {
	*x = ListAlertRulesRequest{}
	mi := &file_containarium_v1_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRulesRequest) ProtoMessage() {}

func (x *ListAlertRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRulesRequest.ProtoReflect.Descriptor instead.
func (*ListAlertRulesRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{5}
}

// ListAlertRulesResponse returns all alert rules
type ListAlertRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AlertRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRulesResponse) Reset() {
	*x = ListAlertRulesResponse{}
	mi := &file_containarium_v1_alert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRulesResponse) ProtoMessage() {}

func (x *ListAlertRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRulesResponse.ProtoReflect.Descriptor instead.
func (*ListAlertRulesResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{6}
}

func (x *ListAlertRulesResponse) GetRules() []*AlertRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// UpdateAlertRuleRequest updates an existing alert rule
type UpdateAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Expr          string                 `protobuf:"bytes,3,opt,name=expr,proto3" json:"expr,omitempty"`
	Duration      string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enabled       *bool                  `protobuf:"varint,9,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRuleRequest) Reset() {
	*x = UpdateAlertRuleRequest{}
	mi := &file_containarium_v1_alert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRuleRequest) ProtoMessage() {}

func (x *UpdateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAlertRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *UpdateAlertRuleRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *UpdateAlertRuleRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// UpdateAlertRuleResponse returns the updated alert rule
type UpdateAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRuleResponse) Reset() {
	*x = UpdateAlertRuleResponse{}
	mi := &file_containarium_v1_alert_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRuleResponse) ProtoMessage() {}

func (x *UpdateAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAlertRuleResponse) GetRule() *AlertRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// DeleteAlertRuleRequest deletes an alert rule by ID
type DeleteAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRuleRequest) Reset() {
	*x = DeleteAlertRuleRequest{}
	mi := &file_containarium_v1_alert_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRuleRequest) ProtoMessage() {}

func (x *DeleteAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAlertRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteAlertRuleResponse confirms deletion
type DeleteAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRuleResponse) Reset() {
	*x = DeleteAlertRuleResponse{}
	mi := &file_containarium_v1_alert_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRuleResponse) ProtoMessage() {}

func (x *DeleteAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{10}
}

// GetAlertingInfoRequest gets the alerting system status
type GetAlertingInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertingInfoRequest) Reset() {
	*x = GetAlertingInfoRequest{}
	mi := &file_containarium_v1_alert_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertingInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertingInfoRequest) ProtoMessage() {}

func (x *GetAlertingInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertingInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAlertingInfoRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{11}
}

// GetAlertingInfoResponse returns alerting system information
type GetAlertingInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the alerting system is configured and running
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// vmalert health status
	VmalertStatus string `protobuf:"bytes,2,opt,name=vmalert_status,json=vmalertStatus,proto3" json:"vmalert_status,omitempty"`
	// Alertmanager health status
	AlertmanagerStatus string `protobuf:"bytes,3,opt,name=alertmanager_status,json=alertmanagerStatus,proto3" json:"alertmanager_status,omitempty"`
	// Configured webhook URL (masked for security)
	WebhookUrl string `protobuf:"bytes,4,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	// Number of active alert rules (default + custom)
	TotalRules int32 `protobuf:"varint,5,opt,name=total_rules,json=totalRules,proto3" json:"total_rules,omitempty"`
	// Number of custom alert rules
	CustomRules int32 `protobuf:"varint,6,opt,name=custom_rules,json=customRules,proto3" json:"custom_rules,omitempty"`
	// Whether a webhook HMAC signing secret is configured
	WebhookSecretConfigured bool `protobuf:"varint,7,opt,name=webhook_secret_configured,json=webhookSecretConfigured,proto3" json:"webhook_secret_configured,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetAlertingInfoResponse) Reset() {
	*x = GetAlertingInfoResponse{}
	mi := &file_containarium_v1_alert_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertingInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertingInfoResponse) ProtoMessage() {}

func (x *GetAlertingInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertingInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAlertingInfoResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{12}
}

func (x *GetAlertingInfoResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetAlertingInfoResponse) GetVmalertStatus() string {
	if x != nil {
		return x.VmalertStatus
	}
	return ""
}

func (x *GetAlertingInfoResponse) GetAlertmanagerStatus() string {
	if x != nil {
		return x.AlertmanagerStatus
	}
	return ""
}

func (x *GetAlertingInfoResponse) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *GetAlertingInfoResponse) GetTotalRules() int32 {
	if x != nil {
		return x.TotalRules
	}
	return 0
}

func (x *GetAlertingInfoResponse) GetCustomRules() int32 {
	if x != nil {
		return x.CustomRules
	}
	return 0
}

func (x *GetAlertingInfoResponse) GetWebhookSecretConfigured() bool {
	if x != nil {
		return x.WebhookSecretConfigured
	}
	return false
}

// ListDefaultAlertRulesRequest lists the built-in default alert rules
type ListDefaultAlertRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefaultAlertRulesRequest) Reset() {
	*x = ListDefaultAlertRulesRequest{}
	mi := &file_containarium_v1_alert_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefaultAlertRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefaultAlertRulesRequest) ProtoMessage() {}

func (x *ListDefaultAlertRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefaultAlertRulesRequest.ProtoReflect.Descriptor instead.
func (*ListDefaultAlertRulesRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{13}
}

// ListDefaultAlertRulesResponse returns the built-in default alert rules
type ListDefaultAlertRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AlertRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefaultAlertRulesResponse) Reset() {
	*x = ListDefaultAlertRulesResponse{}
	mi := &file_containarium_v1_alert_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefaultAlertRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefaultAlertRulesResponse) ProtoMessage() {}

func (x *ListDefaultAlertRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefaultAlertRulesResponse.ProtoReflect.Descriptor instead.
func (*ListDefaultAlertRulesResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{14}
}

func (x *ListDefaultAlertRulesResponse) GetRules() []*AlertRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// UpdateAlertingConfigRequest updates alerting system configuration
type UpdateAlertingConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Webhook URL for alert notifications (empty string to disable)
	WebhookUrl string `protobuf:"bytes,1,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	// When true, the server generates a new HMAC signing secret for webhook payloads
	GenerateWebhookSecret bool `protobuf:"varint,2,opt,name=generate_webhook_secret,json=generateWebhookSecret,proto3" json:"generate_webhook_secret,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateAlertingConfigRequest) Reset() {
	*x = UpdateAlertingConfigRequest{}
	mi := &file_containarium_v1_alert_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertingConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertingConfigRequest) ProtoMessage() {}

func (x *UpdateAlertingConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertingConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertingConfigRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateAlertingConfigRequest) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *UpdateAlertingConfigRequest) GetGenerateWebhookSecret() bool {
	if x != nil {
		return x.GenerateWebhookSecret
	}
	return false
}

// UpdateAlertingConfigResponse returns updated alerting configuration
type UpdateAlertingConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configured webhook URL (masked for security)
	WebhookUrl string `protobuf:"bytes,1,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	// Whether the configuration was applied successfully
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// The generated webhook secret (returned only once when generate_webhook_secret=true)
	WebhookSecret string `protobuf:"bytes,3,opt,name=webhook_secret,json=webhookSecret,proto3" json:"webhook_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertingConfigResponse) Reset() {
	*x = UpdateAlertingConfigResponse{}
	mi := &file_containarium_v1_alert_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertingConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertingConfigResponse) ProtoMessage() {}

func (x *UpdateAlertingConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertingConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlertingConfigResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateAlertingConfigResponse) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *UpdateAlertingConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateAlertingConfigResponse) GetWebhookSecret() string {
	if x != nil {
		return x.WebhookSecret
	}
	return ""
}

// TestWebhookRequest triggers a test notification to the configured webhook
type TestWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWebhookRequest) Reset() {
	*x = TestWebhookRequest{}
	mi := &file_containarium_v1_alert_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWebhookRequest) ProtoMessage() {}

func (x *TestWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWebhookRequest.ProtoReflect.Descriptor instead.
func (*TestWebhookRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{17}
}

// TestWebhookResponse returns the result of the test
type TestWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the test notification was sent successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// HTTP status code from the webhook endpoint
	StatusCode int32 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Human-readable message
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWebhookResponse) Reset() {
	*x = TestWebhookResponse{}
	mi := &file_containarium_v1_alert_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWebhookResponse) ProtoMessage() {}

func (x *TestWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWebhookResponse.ProtoReflect.Descriptor instead.
func (*TestWebhookResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{18}
}

func (x *TestWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestWebhookResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *TestWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// WebhookDelivery represents a single webhook delivery attempt
type WebhookDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AlertName     string                 `protobuf:"bytes,3,opt,name=alert_name,json=alertName,proto3" json:"alert_name,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`                           // "relay" or "test"
	WebhookUrl    string                 `protobuf:"bytes,5,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"` // masked
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	HttpStatus    int32                  `protobuf:"varint,7,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	PayloadSize   int32                  `protobuf:"varint,9,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	DurationMs    int32                  `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookDelivery) Reset() {
	*x = WebhookDelivery{}
	mi := &file_containarium_v1_alert_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDelivery) ProtoMessage() {}

func (x *WebhookDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookDelivery.ProtoReflect.Descriptor instead.
func (*WebhookDelivery) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{19}
}

func (x *WebhookDelivery) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebhookDelivery) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *WebhookDelivery) GetAlertName() string {
	if x != nil {
		return x.AlertName
	}
	return ""
}

func (x *WebhookDelivery) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WebhookDelivery) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *WebhookDelivery) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WebhookDelivery) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *WebhookDelivery) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WebhookDelivery) GetPayloadSize() int32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *WebhookDelivery) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// ListWebhookDeliveriesRequest lists webhook delivery history
type ListWebhookDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhookDeliveriesRequest) Reset() {
	*x = ListWebhookDeliveriesRequest{}
	mi := &file_containarium_v1_alert_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhookDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhookDeliveriesRequest) ProtoMessage() {}

func (x *ListWebhookDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhookDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*ListWebhookDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{20}
}

func (x *ListWebhookDeliveriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWebhookDeliveriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListWebhookDeliveriesResponse returns webhook delivery history
type ListWebhookDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*WebhookDelivery     `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhookDeliveriesResponse) Reset() {
	*x = ListWebhookDeliveriesResponse{}
	mi := &file_containarium_v1_alert_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhookDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhookDeliveriesResponse) ProtoMessage() {}

func (x *ListWebhookDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_alert_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhookDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*ListWebhookDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_alert_proto_rawDescGZIP(), []int{21}
}

func (x *ListWebhookDeliveriesResponse) GetDeliveries() []*WebhookDelivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *ListWebhookDeliveriesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_containarium_v1_alert_proto protoreflect.FileDescriptor

const file_containarium_v1_alert_proto_rawDesc = "" +
	"\n" +
	"\x1bcontainarium/v1/alert.proto\x12\x0fcontainarium.v1\"\xff\x03\n" +
	"\tAlertRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04expr\x18\x03 \x01(\tR\x04expr\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12>\n" +
	"\x06labels\x18\a \x03(\v2&.containarium.v1.AlertRule.LabelsEntryR\x06labels\x12M\n" +
	"\vannotations\x18\b \x03(\v2+.containarium.v1.AlertRule.AnnotationsEntryR\vannotations\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x03\n" +
	"\x16CreateAlertRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04expr\x18\x02 \x01(\tR\x04expr\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12K\n" +
	"\x06labels\x18\x06 \x03(\v23.containarium.v1.CreateAlertRuleRequest.LabelsEntryR\x06labels\x12Z\n" +
	"\vannotations\x18\a \x03(\v28.containarium.v1.CreateAlertRuleRequest.AnnotationsEntryR\vannotations\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x17CreateAlertRuleResponse\x12.\n" +
	"\x04rule\x18\x01 \x01(\v2\x1a.containarium.v1.AlertRuleR\x04rule\"%\n" +
	"\x13GetAlertRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x14GetAlertRuleResponse\x12.\n" +
	"\x04rule\x18\x01 \x01(\v2\x1a.containarium.v1.AlertRuleR\x04rule\"\x17\n" +
	"\x15ListAlertRulesRequest\"J\n" +
	"\x16ListAlertRulesResponse\x120\n" +
	"\x05rules\x18\x01 \x03(\v2\x1a.containarium.v1.AlertRuleR\x05rules\"\xf9\x03\n" +
	"\x16UpdateAlertRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04expr\x18\x03 \x01(\tR\x04expr\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12K\n" +
	"\x06labels\x18\a \x03(\v23.containarium.v1.UpdateAlertRuleRequest.LabelsEntryR\x06labels\x12Z\n" +
	"\vannotations\x18\b \x03(\v28.containarium.v1.UpdateAlertRuleRequest.AnnotationsEntryR\vannotations\x12\x1d\n" +
	"\aenabled\x18\t \x01(\bH\x00R\aenabled\x88\x01\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_enabled\"I\n" +
	"\x17UpdateAlertRuleResponse\x12.\n" +
	"\x04rule\x18\x01 \x01(\v2\x1a.containarium.v1.AlertRuleR\x04rule\"(\n" +
	"\x16DeleteAlertRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteAlertRuleResponse\"\x18\n" +
	"\x16GetAlertingInfoRequest\"\xac\x02\n" +
	"\x17GetAlertingInfoResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12%\n" +
	"\x0evmalert_status\x18\x02 \x01(\tR\rvmalertStatus\x12/\n" +
	"\x13alertmanager_status\x18\x03 \x01(\tR\x12alertmanagerStatus\x12\x1f\n" +
	"\vwebhook_url\x18\x04 \x01(\tR\n" +
	"webhookUrl\x12\x1f\n" +
	"\vtotal_rules\x18\x05 \x01(\x05R\n" +
	"totalRules\x12!\n" +
	"\fcustom_rules\x18\x06 \x01(\x05R\vcustomRules\x12:\n" +
	"\x19webhook_secret_configured\x18\a \x01(\bR\x17webhookSecretConfigured\"\x1e\n" +
	"\x1cListDefaultAlertRulesRequest\"Q\n" +
	"\x1dListDefaultAlertRulesResponse\x120\n" +
	"\x05rules\x18\x01 \x03(\v2\x1a.containarium.v1.AlertRuleR\x05rules\"v\n" +
	"\x1bUpdateAlertingConfigRequest\x12\x1f\n" +
	"\vwebhook_url\x18\x01 \x01(\tR\n" +
	"webhookUrl\x126\n" +
	"\x17generate_webhook_secret\x18\x02 \x01(\bR\x15generateWebhookSecret\"\x80\x01\n" +
	"\x1cUpdateAlertingConfigResponse\x12\x1f\n" +
	"\vwebhook_url\x18\x01 \x01(\tR\n" +
	"webhookUrl\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12%\n" +
	"\x0ewebhook_secret\x18\x03 \x01(\tR\rwebhookSecret\"\x14\n" +
	"\x12TestWebhookRequest\"j\n" +
	"\x13TestWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xbb\x02\n" +
	"\x0fWebhookDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"alert_name\x18\x03 \x01(\tR\talertName\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1f\n" +
	"\vwebhook_url\x18\x05 \x01(\tR\n" +
	"webhookUrl\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x1f\n" +
	"\vhttp_status\x18\a \x01(\x05R\n" +
	"httpStatus\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12!\n" +
	"\fpayload_size\x18\t \x01(\x05R\vpayloadSize\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x05R\n" +
	"durationMs\"L\n" +
	"\x1cListWebhookDeliveriesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x82\x01\n" +
	"\x1dListWebhookDeliveriesResponse\x12@\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2 .containarium.v1.WebhookDeliveryR\n" +
	"deliveries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCountBKZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var (
	file_containarium_v1_alert_proto_rawDescOnce sync.Once
	file_containarium_v1_alert_proto_rawDescData []byte
)

func file_containarium_v1_alert_proto_rawDescGZIP() []byte {
	file_containarium_v1_alert_proto_rawDescOnce.Do(func() {
		file_containarium_v1_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containarium_v1_alert_proto_rawDesc), len(file_containarium_v1_alert_proto_rawDesc)))
	})
	return file_containarium_v1_alert_proto_rawDescData
}

var file_containarium_v1_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_containarium_v1_alert_proto_goTypes = []any{
	(*AlertRule)(nil),                     // 0: containarium.v1.AlertRule
	(*CreateAlertRuleRequest)(nil),        // 1: containarium.v1.CreateAlertRuleRequest
	(*CreateAlertRuleResponse)(nil),       // 2: containarium.v1.CreateAlertRuleResponse
	(*GetAlertRuleRequest)(nil),           // 3: containarium.v1.GetAlertRuleRequest
	(*GetAlertRuleResponse)(nil),          // 4: containarium.v1.GetAlertRuleResponse
	(*ListAlertRulesRequest)(nil),         // 5: containarium.v1.ListAlertRulesRequest
	(*ListAlertRulesResponse)(nil),        // 6: containarium.v1.ListAlertRulesResponse
	(*UpdateAlertRuleRequest)(nil),        // 7: containarium.v1.UpdateAlertRuleRequest
	(*UpdateAlertRuleResponse)(nil),       // 8: containarium.v1.UpdateAlertRuleResponse
	(*DeleteAlertRuleRequest)(nil),        // 9: containarium.v1.DeleteAlertRuleRequest
	(*DeleteAlertRuleResponse)(nil),       // 10: containarium.v1.DeleteAlertRuleResponse
	(*GetAlertingInfoRequest)(nil),        // 11: containarium.v1.GetAlertingInfoRequest
	(*GetAlertingInfoResponse)(nil),       // 12: containarium.v1.GetAlertingInfoResponse
	(*ListDefaultAlertRulesRequest)(nil),  // 13: containarium.v1.ListDefaultAlertRulesRequest
	(*ListDefaultAlertRulesResponse)(nil), // 14: containarium.v1.ListDefaultAlertRulesResponse
	(*UpdateAlertingConfigRequest)(nil),   // 15: containarium.v1.UpdateAlertingConfigRequest
	(*UpdateAlertingConfigResponse)(nil),  // 16: containarium.v1.UpdateAlertingConfigResponse
	(*TestWebhookRequest)(nil),            // 17: containarium.v1.TestWebhookRequest
	(*TestWebhookResponse)(nil),           // 18: containarium.v1.TestWebhookResponse
	(*WebhookDelivery)(nil),               // 19: containarium.v1.WebhookDelivery
	(*ListWebhookDeliveriesRequest)(nil),  // 20: containarium.v1.ListWebhookDeliveriesRequest
	(*ListWebhookDeliveriesResponse)(nil), // 21: containarium.v1.ListWebhookDeliveriesResponse
	nil,                                   // 22: containarium.v1.AlertRule.LabelsEntry
	nil,                                   // 23: containarium.v1.AlertRule.AnnotationsEntry
	nil,                                   // 24: containarium.v1.CreateAlertRuleRequest.LabelsEntry
	nil,                                   // 25: containarium.v1.CreateAlertRuleRequest.AnnotationsEntry
	nil,                                   // 26: containarium.v1.UpdateAlertRuleRequest.LabelsEntry
	nil,                                   // 27: containarium.v1.UpdateAlertRuleRequest.AnnotationsEntry
}
var file_containarium_v1_alert_proto_depIdxs = []int32{
	22, // 0: containarium.v1.AlertRule.labels:type_name -> containarium.v1.AlertRule.LabelsEntry
	23, // 1: containarium.v1.AlertRule.annotations:type_name -> containarium.v1.AlertRule.AnnotationsEntry
	24, // 2: containarium.v1.CreateAlertRuleRequest.labels:type_name -> containarium.v1.CreateAlertRuleRequest.LabelsEntry
	25, // 3: containarium.v1.CreateAlertRuleRequest.annotations:type_name -> containarium.v1.CreateAlertRuleRequest.AnnotationsEntry
	0,  // 4: containarium.v1.CreateAlertRuleResponse.rule:type_name -> containarium.v1.AlertRule
	0,  // 5: containarium.v1.GetAlertRuleResponse.rule:type_name -> containarium.v1.AlertRule
	0,  // 6: containarium.v1.ListAlertRulesResponse.rules:type_name -> containarium.v1.AlertRule
	26, // 7: containarium.v1.UpdateAlertRuleRequest.labels:type_name -> containarium.v1.UpdateAlertRuleRequest.LabelsEntry
	27, // 8: containarium.v1.UpdateAlertRuleRequest.annotations:type_name -> containarium.v1.UpdateAlertRuleRequest.AnnotationsEntry
	0,  // 9: containarium.v1.UpdateAlertRuleResponse.rule:type_name -> containarium.v1.AlertRule
	0,  // 10: containarium.v1.ListDefaultAlertRulesResponse.rules:type_name -> containarium.v1.AlertRule
	19, // 11: containarium.v1.ListWebhookDeliveriesResponse.deliveries:type_name -> containarium.v1.WebhookDelivery
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_containarium_v1_alert_proto_init() }
func file_containarium_v1_alert_proto_init() {
	if File_containarium_v1_alert_proto != nil {
		return
	}
	file_containarium_v1_alert_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_alert_proto_rawDesc), len(file_containarium_v1_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_containarium_v1_alert_proto_goTypes,
		DependencyIndexes: file_containarium_v1_alert_proto_depIdxs,
		MessageInfos:      file_containarium_v1_alert_proto_msgTypes,
	}.Build()
	File_containarium_v1_alert_proto = out.File
	file_containarium_v1_alert_proto_goTypes = nil
	file_containarium_v1_alert_proto_depIdxs = nil
}
