// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/audit.proto

package containariumv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SSHSessionPhase mirrors internal/sentinel/sshsession.SessionPhase.
type SSHSessionPhase int32

const (
	SSHSessionPhase_SSH_SESSION_PHASE_UNSPECIFIED SSHSessionPhase = 0
	SSHSessionPhase_SSH_SESSION_PHASE_OPEN        SSHSessionPhase = 1
	SSHSessionPhase_SSH_SESSION_PHASE_CLOSE       SSHSessionPhase = 2
)

// Enum value maps for SSHSessionPhase.
var (
	SSHSessionPhase_name = map[int32]string{
		0: "SSH_SESSION_PHASE_UNSPECIFIED",
		1: "SSH_SESSION_PHASE_OPEN",
		2: "SSH_SESSION_PHASE_CLOSE",
	}
	SSHSessionPhase_value = map[string]int32{
		"SSH_SESSION_PHASE_UNSPECIFIED": 0,
		"SSH_SESSION_PHASE_OPEN":        1,
		"SSH_SESSION_PHASE_CLOSE":       2,
	}
)

func (x SSHSessionPhase) Enum() *SSHSessionPhase {
	p := new(SSHSessionPhase)
	*p = x
	return p
}

func (x SSHSessionPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SSHSessionPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_audit_proto_enumTypes[0].Descriptor()
}

func (SSHSessionPhase) Type() protoreflect.EnumType {
	return &file_containarium_v1_audit_proto_enumTypes[0]
}

func (x SSHSessionPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SSHSessionPhase.Descriptor instead.
func (SSHSessionPhase) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_audit_proto_rawDescGZIP(), []int{0}
}

// SSHAuthMethod mirrors internal/sentinel/sshsession.AuthMethod.
type SSHAuthMethod int32

const (
	SSHAuthMethod_SSH_AUTH_METHOD_UNSPECIFIED SSHAuthMethod = 0
	SSHAuthMethod_SSH_AUTH_METHOD_CERTIFICATE SSHAuthMethod = 1
	SSHAuthMethod_SSH_AUTH_METHOD_PUBLICKEY   SSHAuthMethod = 2
	// The offered key could not be parsed; credential fields are empty.
	SSHAuthMethod_SSH_AUTH_METHOD_UNKNOWN SSHAuthMethod = 3
)

// Enum value maps for SSHAuthMethod.
var (
	SSHAuthMethod_name = map[int32]string{
		0: "SSH_AUTH_METHOD_UNSPECIFIED",
		1: "SSH_AUTH_METHOD_CERTIFICATE",
		2: "SSH_AUTH_METHOD_PUBLICKEY",
		3: "SSH_AUTH_METHOD_UNKNOWN",
	}
	SSHAuthMethod_value = map[string]int32{
		"SSH_AUTH_METHOD_UNSPECIFIED": 0,
		"SSH_AUTH_METHOD_CERTIFICATE": 1,
		"SSH_AUTH_METHOD_PUBLICKEY":   2,
		"SSH_AUTH_METHOD_UNKNOWN":     3,
	}
)

func (x SSHAuthMethod) Enum() *SSHAuthMethod {
	p := new(SSHAuthMethod)
	*p = x
	return p
}

func (x SSHAuthMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SSHAuthMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_audit_proto_enumTypes[1].Descriptor()
}

func (SSHAuthMethod) Type() protoreflect.EnumType {
	return &file_containarium_v1_audit_proto_enumTypes[1]
}

func (x SSHAuthMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SSHAuthMethod.Descriptor instead.
func (SSHAuthMethod) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_audit_proto_rawDescGZIP(), []int{1}
}

// SSHCloseReason mirrors internal/sentinel/sshsession.CloseReason. Set only
// on a CLOSE record.
type SSHCloseReason int32

const (
	SSHCloseReason_SSH_CLOSE_REASON_UNSPECIFIED    SSHCloseReason = 0
	SSHCloseReason_SSH_CLOSE_REASON_NORMAL         SSHCloseReason = 1
	SSHCloseReason_SSH_CLOSE_REASON_UPSTREAM_GONE  SSHCloseReason = 2
	SSHCloseReason_SSH_CLOSE_REASON_PROXY_SHUTDOWN SSHCloseReason = 3
	SSHCloseReason_SSH_CLOSE_REASON_ERROR          SSHCloseReason = 4
	// Emitted by the shipper's --reconcile for an OPEN record that never got
	// a CLOSE (plugin hard-killed), once it is older than the orphan
	// threshold. Never written by the plugin itself.
	SSHCloseReason_SSH_CLOSE_REASON_UNKNOWN_ORPHAN SSHCloseReason = 5
)

// Enum value maps for SSHCloseReason.
var (
	SSHCloseReason_name = map[int32]string{
		0: "SSH_CLOSE_REASON_UNSPECIFIED",
		1: "SSH_CLOSE_REASON_NORMAL",
		2: "SSH_CLOSE_REASON_UPSTREAM_GONE",
		3: "SSH_CLOSE_REASON_PROXY_SHUTDOWN",
		4: "SSH_CLOSE_REASON_ERROR",
		5: "SSH_CLOSE_REASON_UNKNOWN_ORPHAN",
	}
	SSHCloseReason_value = map[string]int32{
		"SSH_CLOSE_REASON_UNSPECIFIED":    0,
		"SSH_CLOSE_REASON_NORMAL":         1,
		"SSH_CLOSE_REASON_UPSTREAM_GONE":  2,
		"SSH_CLOSE_REASON_PROXY_SHUTDOWN": 3,
		"SSH_CLOSE_REASON_ERROR":          4,
		"SSH_CLOSE_REASON_UNKNOWN_ORPHAN": 5,
	}
)

func (x SSHCloseReason) Enum() *SSHCloseReason {
	p := new(SSHCloseReason)
	*p = x
	return p
}

func (x SSHCloseReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SSHCloseReason) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_audit_proto_enumTypes[2].Descriptor()
}

func (SSHCloseReason) Type() protoreflect.EnumType {
	return &file_containarium_v1_audit_proto_enumTypes[2]
}

func (x SSHCloseReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SSHCloseReason.Descriptor instead.
func (SSHCloseReason) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_audit_proto_rawDescGZIP(), []int{2}
}

// IngestOutcome is the per-record result of an OK ingest call.
type IngestOutcome int32

const (
	IngestOutcome_INGEST_OUTCOME_UNSPECIFIED IngestOutcome = 0
	IngestOutcome_INGEST_OUTCOME_INSERTED    IngestOutcome = 1
	IngestOutcome_INGEST_OUTCOME_DUPLICATE   IngestOutcome = 2
)

// Enum value maps for IngestOutcome.
var (
	IngestOutcome_name = map[int32]string{
		0: "INGEST_OUTCOME_UNSPECIFIED",
		1: "INGEST_OUTCOME_INSERTED",
		2: "INGEST_OUTCOME_DUPLICATE",
	}
	IngestOutcome_value = map[string]int32{
		"INGEST_OUTCOME_UNSPECIFIED": 0,
		"INGEST_OUTCOME_INSERTED":    1,
		"INGEST_OUTCOME_DUPLICATE":   2,
	}
)

func (x IngestOutcome) Enum() *IngestOutcome {
	p := new(IngestOutcome)
	*p = x
	return p
}

func (x IngestOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_audit_proto_enumTypes[3].Descriptor()
}

func (IngestOutcome) Type() protoreflect.EnumType {
	return &file_containarium_v1_audit_proto_enumTypes[3]
}

func (x IngestOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestOutcome.Descriptor instead.
func (IngestOutcome) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_audit_proto_rawDescGZIP(), []int{3}
}

// SSHSessionCredential is the non-secret handle identifying the credential
// a session authenticated with — fingerprints, a key_id and a serial, never
// key material.
type SSHSessionCredential struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Serial           uint64                 `protobuf:"varint,2,opt,name=serial,proto3" json:"serial,omitempty"`
	CaKeyFingerprint string                 `protobuf:"bytes,3,opt,name=ca_key_fingerprint,json=caKeyFingerprint,proto3" json:"ca_key_fingerprint,omitempty"`
	KeyFingerprint   string                 `protobuf:"bytes,4,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SSHSessionCredential) Reset() {
	*x = SSHSessionCredential{}
	mi := &file_containarium_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHSessionCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHSessionCredential) ProtoMessage() {}

func (x *SSHSessionCredential) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHSessionCredential.ProtoReflect.Descriptor instead.
func (*SSHSessionCredential) Descriptor() ([]byte, []int) {
	return file_containarium_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *SSHSessionCredential) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SSHSessionCredential) GetSerial() uint64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *SSHSessionCredential) GetCaKeyFingerprint() string {
	if x != nil {
		return x.CaKeyFingerprint
	}
	return ""
}

func (x *SSHSessionCredential) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

// SSHSessionRecord is one session lifecycle event, field for field the
// sentinel's sshsession.Record.
type SSHSessionRecord struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SessionId  string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Phase      SSHSessionPhase        `protobuf:"varint,2,opt,name=phase,proto3,enum=containarium.v1.SSHSessionPhase" json:"phase,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Real downstream (client-facing) address.
	ClientIp   string `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientPort int32  `protobuf:"varint,5,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	// SSH username presented; under certificate auth this names the target
	// account, the credential names the person.
	Login string `protobuf:"bytes,6,opt,name=login,proto3" json:"login,omitempty"`
	// Backend endpoint (host:port) the sentinel routed the login to; may be
	// empty if unresolvable at record time.
	Target     string                `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	AuthMethod SSHAuthMethod         `protobuf:"varint,8,opt,name=auth_method,json=authMethod,proto3,enum=containarium.v1.SSHAuthMethod" json:"auth_method,omitempty"`
	Credential *SSHSessionCredential `protobuf:"bytes,9,opt,name=credential,proto3" json:"credential,omitempty"`
	// Set only when phase == SSH_SESSION_PHASE_CLOSE.
	CloseReason   SSHCloseReason `protobuf:"varint,10,opt,name=close_reason,json=closeReason,proto3,enum=containarium.v1.SSHCloseReason" json:"close_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHSessionRecord) Reset() {
	*x = SSHSessionRecord{}
	mi := &file_containarium_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHSessionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHSessionRecord) ProtoMessage() {}

func (x *SSHSessionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHSessionRecord.ProtoReflect.Descriptor instead.
func (*SSHSessionRecord) Descriptor() ([]byte, []int) {
	return file_containarium_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *SSHSessionRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SSHSessionRecord) GetPhase() SSHSessionPhase {
	if x != nil {
		return x.Phase
	}
	return SSHSessionPhase_SSH_SESSION_PHASE_UNSPECIFIED
}

func (x *SSHSessionRecord) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *SSHSessionRecord) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SSHSessionRecord) GetClientPort() int32 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *SSHSessionRecord) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SSHSessionRecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SSHSessionRecord) GetAuthMethod() SSHAuthMethod {
	if x != nil {
		return x.AuthMethod
	}
	return SSHAuthMethod_SSH_AUTH_METHOD_UNSPECIFIED
}

func (x *SSHSessionRecord) GetCredential() *SSHSessionCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *SSHSessionRecord) GetCloseReason() SSHCloseReason {
	if x != nil {
		return x.CloseReason
	}
	return SSHCloseReason_SSH_CLOSE_REASON_UNSPECIFIED
}

type IngestSSHSessionRecordsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1..500 records in file order.
	Records []*SSHSessionRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// Informational identifier of the shipping sentinel; recorded in each
	// row's detail, never used for authorization.
	SentinelId    string `protobuf:"bytes,2,opt,name=sentinel_id,json=sentinelId,proto3" json:"sentinel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSSHSessionRecordsRequest) Reset() {
	*x = IngestSSHSessionRecordsRequest{}
	mi := &file_containarium_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSSHSessionRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSSHSessionRecordsRequest) ProtoMessage() {}

func (x *IngestSSHSessionRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSSHSessionRecordsRequest.ProtoReflect.Descriptor instead.
func (*IngestSSHSessionRecordsRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *IngestSSHSessionRecordsRequest) GetRecords() []*SSHSessionRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *IngestSSHSessionRecordsRequest) GetSentinelId() string {
	if x != nil {
		return x.SentinelId
	}
	return ""
}

type IngestSSHSessionRecordsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Same length and order as the request's records.
	Outcomes      []IngestOutcome `protobuf:"varint,1,rep,packed,name=outcomes,proto3,enum=containarium.v1.IngestOutcome" json:"outcomes,omitempty"`
	Inserted      int32           `protobuf:"varint,2,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Duplicates    int32           `protobuf:"varint,3,opt,name=duplicates,proto3" json:"duplicates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSSHSessionRecordsResponse) Reset() {
	*x = IngestSSHSessionRecordsResponse{}
	mi := &file_containarium_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSSHSessionRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSSHSessionRecordsResponse) ProtoMessage() {}

func (x *IngestSSHSessionRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSSHSessionRecordsResponse.ProtoReflect.Descriptor instead.
func (*IngestSSHSessionRecordsResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *IngestSSHSessionRecordsResponse) GetOutcomes() []IngestOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *IngestSSHSessionRecordsResponse) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *IngestSSHSessionRecordsResponse) GetDuplicates() int32 {
	if x != nil {
		return x.Duplicates
	}
	return 0
}

var File_containarium_v1_audit_proto protoreflect.FileDescriptor

const file_containarium_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x1bcontainarium/v1/audit.proto\x12\x0fcontainarium.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x9c\x01\n" +
	"\x14SSHSessionCredential\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\x04R\x06serial\x12,\n" +
	"\x12ca_key_fingerprint\x18\x03 \x01(\tR\x10caKeyFingerprint\x12'\n" +
	"\x0fkey_fingerprint\x18\x04 \x01(\tR\x0ekeyFingerprint\"\xde\x03\n" +
	"\x10SSHSessionRecord\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x126\n" +
	"\x05phase\x18\x02 \x01(\x0e2 .containarium.v1.SSHSessionPhaseR\x05phase\x12;\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vclient_port\x18\x05 \x01(\x05R\n" +
	"clientPort\x12\x14\n" +
	"\x05login\x18\x06 \x01(\tR\x05login\x12\x16\n" +
	"\x06target\x18\a \x01(\tR\x06target\x12?\n" +
	"\vauth_method\x18\b \x01(\x0e2\x1e.containarium.v1.SSHAuthMethodR\n" +
	"authMethod\x12E\n" +
	"\n" +
	"credential\x18\t \x01(\v2%.containarium.v1.SSHSessionCredentialR\n" +
	"credential\x12B\n" +
	"\fclose_reason\x18\n" +
	" \x01(\x0e2\x1f.containarium.v1.SSHCloseReasonR\vcloseReason\"~\n" +
	"\x1eIngestSSHSessionRecordsRequest\x12;\n" +
	"\arecords\x18\x01 \x03(\v2!.containarium.v1.SSHSessionRecordR\arecords\x12\x1f\n" +
	"\vsentinel_id\x18\x02 \x01(\tR\n" +
	"sentinelId\"\x99\x01\n" +
	"\x1fIngestSSHSessionRecordsResponse\x12:\n" +
	"\boutcomes\x18\x01 \x03(\x0e2\x1e.containarium.v1.IngestOutcomeR\boutcomes\x12\x1a\n" +
	"\binserted\x18\x02 \x01(\x05R\binserted\x12\x1e\n" +
	"\n" +
	"duplicates\x18\x03 \x01(\x05R\n" +
	"duplicates*m\n" +
	"\x0fSSHSessionPhase\x12!\n" +
	"\x1dSSH_SESSION_PHASE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SSH_SESSION_PHASE_OPEN\x10\x01\x12\x1b\n" +
	"\x17SSH_SESSION_PHASE_CLOSE\x10\x02*\x8d\x01\n" +
	"\rSSHAuthMethod\x12\x1f\n" +
	"\x1bSSH_AUTH_METHOD_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bSSH_AUTH_METHOD_CERTIFICATE\x10\x01\x12\x1d\n" +
	"\x19SSH_AUTH_METHOD_PUBLICKEY\x10\x02\x12\x1b\n" +
	"\x17SSH_AUTH_METHOD_UNKNOWN\x10\x03*\xd9\x01\n" +
	"\x0eSSHCloseReason\x12 \n" +
	"\x1cSSH_CLOSE_REASON_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SSH_CLOSE_REASON_NORMAL\x10\x01\x12\"\n" +
	"\x1eSSH_CLOSE_REASON_UPSTREAM_GONE\x10\x02\x12#\n" +
	"\x1fSSH_CLOSE_REASON_PROXY_SHUTDOWN\x10\x03\x12\x1a\n" +
	"\x16SSH_CLOSE_REASON_ERROR\x10\x04\x12#\n" +
	"\x1fSSH_CLOSE_REASON_UNKNOWN_ORPHAN\x10\x05*j\n" +
	"\rIngestOutcome\x12\x1e\n" +
	"\x1aINGEST_OUTCOME_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17INGEST_OUTCOME_INSERTED\x10\x01\x12\x1c\n" +
	"\x18INGEST_OUTCOME_DUPLICATE\x10\x022\xa6\x03\n" +
	"\fAuditService\x12\x95\x03\n" +
	"\x17IngestSSHSessionRecords\x12/.containarium.v1.IngestSSHSessionRecordsRequest\x1a0.containarium.v1.IngestSSHSessionRecordsResponse\"\x96\x02\x92A\xea\x01\n" +
	"\x05Audit\x12#Ingest sentinel SSH session records\x1a\xbb\x01Append sentinel SSH session open/close records to this backend's tamper-evident audit chain. Idempotent per (session_id, phase); all-or-nothing per batch. Requires the audit:ingest scope.\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/audit/ssh-sessions/ingestBKZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var (
	file_containarium_v1_audit_proto_rawDescOnce sync.Once
	file_containarium_v1_audit_proto_rawDescData []byte
)

func file_containarium_v1_audit_proto_rawDescGZIP() []byte {
	file_containarium_v1_audit_proto_rawDescOnce.Do(func() {
		file_containarium_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containarium_v1_audit_proto_rawDesc), len(file_containarium_v1_audit_proto_rawDesc)))
	})
	return file_containarium_v1_audit_proto_rawDescData
}

var file_containarium_v1_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_containarium_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_containarium_v1_audit_proto_goTypes = []any{
	(SSHSessionPhase)(0),                    // 0: containarium.v1.SSHSessionPhase
	(SSHAuthMethod)(0),                      // 1: containarium.v1.SSHAuthMethod
	(SSHCloseReason)(0),                     // 2: containarium.v1.SSHCloseReason
	(IngestOutcome)(0),                      // 3: containarium.v1.IngestOutcome
	(*SSHSessionCredential)(nil),            // 4: containarium.v1.SSHSessionCredential
	(*SSHSessionRecord)(nil),                // 5: containarium.v1.SSHSessionRecord
	(*IngestSSHSessionRecordsRequest)(nil),  // 6: containarium.v1.IngestSSHSessionRecordsRequest
	(*IngestSSHSessionRecordsResponse)(nil), // 7: containarium.v1.IngestSSHSessionRecordsResponse
	(*timestamppb.Timestamp)(nil),           // 8: google.protobuf.Timestamp
}
var file_containarium_v1_audit_proto_depIdxs = []int32{
	0, // 0: containarium.v1.SSHSessionRecord.phase:type_name -> containarium.v1.SSHSessionPhase
	8, // 1: containarium.v1.SSHSessionRecord.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 2: containarium.v1.SSHSessionRecord.auth_method:type_name -> containarium.v1.SSHAuthMethod
	4, // 3: containarium.v1.SSHSessionRecord.credential:type_name -> containarium.v1.SSHSessionCredential
	2, // 4: containarium.v1.SSHSessionRecord.close_reason:type_name -> containarium.v1.SSHCloseReason
	5, // 5: containarium.v1.IngestSSHSessionRecordsRequest.records:type_name -> containarium.v1.SSHSessionRecord
	3, // 6: containarium.v1.IngestSSHSessionRecordsResponse.outcomes:type_name -> containarium.v1.IngestOutcome
	6, // 7: containarium.v1.AuditService.IngestSSHSessionRecords:input_type -> containarium.v1.IngestSSHSessionRecordsRequest
	7, // 8: containarium.v1.AuditService.IngestSSHSessionRecords:output_type -> containarium.v1.IngestSSHSessionRecordsResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_containarium_v1_audit_proto_init() }
func file_containarium_v1_audit_proto_init() {
	if File_containarium_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_audit_proto_rawDesc), len(file_containarium_v1_audit_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containarium_v1_audit_proto_goTypes,
		DependencyIndexes: file_containarium_v1_audit_proto_depIdxs,
		EnumInfos:         file_containarium_v1_audit_proto_enumTypes,
		MessageInfos:      file_containarium_v1_audit_proto_msgTypes,
	}.Build()
	File_containarium_v1_audit_proto = out.File
	file_containarium_v1_audit_proto_goTypes = nil
	file_containarium_v1_audit_proto_depIdxs = nil
}
