// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/backup.proto

package containariumv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BackupDestination is where a logical dump is stored *off* the database
// host. The whole point of the feature is getting the data off-box, so a
// destination is always required — there is no "stay on the same disk"
// option (a dump that shares a failure domain with the database it came
// from is not a backup; see docs/DB-BACKUP-OPERATIONS.md).
type BackupDestination int32

const (
	// Unset — the daemon rejects a create with this value.
	BackupDestination_BACKUP_DESTINATION_UNSPECIFIED BackupDestination = 0
	// A backup directory on the daemon host, distinct from the container's
	// own data disk. Survives container/disk loss but NOT host loss — use
	// for dev or as a staging tier in front of an off-host copy.
	BackupDestination_BACKUP_DESTINATION_LOCAL BackupDestination = 1
	// A Google Cloud Storage bucket, written via the host's `gcloud`
	// (`gcloud storage cp`). True off-host durability; the recommended
	// production destination.
	BackupDestination_BACKUP_DESTINATION_GCS BackupDestination = 2
)

// Enum value maps for BackupDestination.
var (
	BackupDestination_name = map[int32]string{
		0: "BACKUP_DESTINATION_UNSPECIFIED",
		1: "BACKUP_DESTINATION_LOCAL",
		2: "BACKUP_DESTINATION_GCS",
	}
	BackupDestination_value = map[string]int32{
		"BACKUP_DESTINATION_UNSPECIFIED": 0,
		"BACKUP_DESTINATION_LOCAL":       1,
		"BACKUP_DESTINATION_GCS":         2,
	}
)

func (x BackupDestination) Enum() *BackupDestination {
	p := new(BackupDestination)
	*p = x
	return p
}

func (x BackupDestination) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupDestination) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_backup_proto_enumTypes[0].Descriptor()
}

func (BackupDestination) Type() protoreflect.EnumType {
	return &file_containarium_v1_backup_proto_enumTypes[0]
}

func (x BackupDestination) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupDestination.Descriptor instead.
func (BackupDestination) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{0}
}

// VerificationResult is the outcome of a restore test. A backup whose
// bytes are intact but which cannot be loaded by the engine is FAILED —
// that distinction is the whole point of verification (see #1159).
type VerificationResult int32

const (
	// Never verified, or the outcome could not be determined.
	VerificationResult_VERIFICATION_RESULT_UNSPECIFIED VerificationResult = 0
	// The dump restored into a scratch database and passed every
	// engine-appropriate sanity check.
	VerificationResult_VERIFICATION_RESULT_PASSED VerificationResult = 1
	// The dump could not be restored, or restored but failed a sanity
	// check. `error` carries the engine's own message.
	VerificationResult_VERIFICATION_RESULT_FAILED VerificationResult = 2
)

// Enum value maps for VerificationResult.
var (
	VerificationResult_name = map[int32]string{
		0: "VERIFICATION_RESULT_UNSPECIFIED",
		1: "VERIFICATION_RESULT_PASSED",
		2: "VERIFICATION_RESULT_FAILED",
	}
	VerificationResult_value = map[string]int32{
		"VERIFICATION_RESULT_UNSPECIFIED": 0,
		"VERIFICATION_RESULT_PASSED":      1,
		"VERIFICATION_RESULT_FAILED":      2,
	}
)

func (x VerificationResult) Enum() *VerificationResult {
	p := new(VerificationResult)
	*p = x
	return p
}

func (x VerificationResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationResult) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_backup_proto_enumTypes[1].Descriptor()
}

func (VerificationResult) Type() protoreflect.EnumType {
	return &file_containarium_v1_backup_proto_enumTypes[1]
}

func (x VerificationResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationResult.Descriptor instead.
func (VerificationResult) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{1}
}

// BackupRecord is the metadata index entry for one stored dump. The dump
// itself lives at `location`; this record is persisted as a small JSON
// sidecar in the daemon's backup directory so `ListBackups` works without
// a database dependency (the thing we are backing up may itself be down).
type BackupRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier: "<username>-<database>-<UTC timestamp>"
	// (e.g. "alice-app-20260605T130405Z"). Used by Get/Restore/Delete.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant (username) whose container's database was dumped.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// Logical database name that was dumped.
	Database string `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	// RFC3339 UTC timestamp of when the dump completed.
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Size of the compressed custom-format dump, in bytes.
	SizeBytes int64 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// SHA-256 of the dump bytes, for integrity verification on restore.
	Sha256 string `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Where the dump is stored.
	Destination BackupDestination `protobuf:"varint,7,opt,name=destination,proto3,enum=containarium.v1.BackupDestination" json:"destination,omitempty"`
	// Concrete location of the dump: a host path for LOCAL, a gs:// URI
	// for GCS.
	Location string `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	// Database engine. "postgres" is the only engine in v1.
	Engine string `protobuf:"bytes,9,opt,name=engine,proto3" json:"engine,omitempty"`
	// Outcome of the most recent restore test, unset until the backup has
	// been verified. A recorded sha256 proves the bytes are intact; only
	// this proves the dump is restorable (#1159).
	LastVerification *BackupVerification `protobuf:"bytes,10,opt,name=last_verification,json=lastVerification,proto3" json:"last_verification,omitempty"`
	// Number of user relations (tables and partitioned tables, excluding
	// system catalogs) in the source database at dump time — the manifest
	// a restore test compares the restored schema against.
	//
	// Optional because it is absent on backups taken before verification
	// existed, and because a source that cannot be queried still produces
	// a valid dump. Unset means "no manifest": verification records what
	// it found but has nothing to compare it to.
	RelationCount *int64 `protobuf:"varint,11,opt,name=relation_count,json=relationCount,proto3,oneof" json:"relation_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRecord) Reset() {
	*x = BackupRecord{}
	mi := &file_containarium_v1_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRecord) ProtoMessage() {}

func (x *BackupRecord) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRecord.ProtoReflect.Descriptor instead.
func (*BackupRecord) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackupRecord) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BackupRecord) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *BackupRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BackupRecord) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BackupRecord) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BackupRecord) GetDestination() BackupDestination {
	if x != nil {
		return x.Destination
	}
	return BackupDestination_BACKUP_DESTINATION_UNSPECIFIED
}

func (x *BackupRecord) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *BackupRecord) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *BackupRecord) GetLastVerification() *BackupVerification {
	if x != nil {
		return x.LastVerification
	}
	return nil
}

func (x *BackupRecord) GetRelationCount() int64 {
	if x != nil && x.RelationCount != nil {
		return *x.RelationCount
	}
	return 0
}

// VerificationCheck is one engine-appropriate assertion made during a
// restore test, recorded individually so the evidence shows *what* was
// checked rather than just a pass/fail bit.
type VerificationCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Check identifier, e.g. "restore", "connect", "relation_count".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether this individual check passed.
	Passed bool `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	// Human-readable outcome, e.g. "42 relations in scratch database".
	// For a failing check this carries the engine's own error text.
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationCheck) Reset() {
	*x = VerificationCheck{}
	mi := &file_containarium_v1_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationCheck) ProtoMessage() {}

func (x *VerificationCheck) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationCheck.ProtoReflect.Descriptor instead.
func (*VerificationCheck) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{1}
}

func (x *VerificationCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerificationCheck) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *VerificationCheck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// BackupVerification is the audit artifact for one restore test: who ran
// it, when, against what, and what the engine said. Persisted on the
// BackupRecord so `ListBackups` can answer "last verified" and so the
// evidence outlives the run that produced it (ISO 27001 A.8.13 wants
// backups *tested*, not just taken).
type BackupVerification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC3339 UTC timestamp of when verification completed.
	VerifiedAt string `protobuf:"bytes,1,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	// Outcome.
	Result VerificationResult `protobuf:"varint,2,opt,name=result,proto3,enum=containarium.v1.VerificationResult" json:"result,omitempty"`
	// The engine's own error when result is FAILED — pg_restore's own
	// message, so an operator sees why the dump would not load rather
	// than a wrapper's summary. Empty on success. This is engine stderr
	// captured verbatim: it is persisted and returned over the API, so
	// treat it with the same care as any other diagnostic output.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Container the dump was restored into. Always distinct from the
	// container the backup was taken from.
	TargetContainer string `protobuf:"bytes,4,opt,name=target_container,json=targetContainer,proto3" json:"target_container,omitempty"`
	// Throwaway database created for the test and dropped afterwards.
	ScratchDatabase string `protobuf:"bytes,5,opt,name=scratch_database,json=scratchDatabase,proto3" json:"scratch_database,omitempty"`
	// Wall-clock duration of the restore test.
	DurationMs int64 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Authenticated subject that requested verification, for the "who"
	// half of the audit record. Empty when unauthenticated (dev mode).
	VerifiedBy string `protobuf:"bytes,7,opt,name=verified_by,json=verifiedBy,proto3" json:"verified_by,omitempty"`
	// Individual checks performed, in execution order.
	Checks        []*VerificationCheck `protobuf:"bytes,8,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupVerification) Reset() {
	*x = BackupVerification{}
	mi := &file_containarium_v1_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupVerification) ProtoMessage() {}

func (x *BackupVerification) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupVerification.ProtoReflect.Descriptor instead.
func (*BackupVerification) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{2}
}

func (x *BackupVerification) GetVerifiedAt() string {
	if x != nil {
		return x.VerifiedAt
	}
	return ""
}

func (x *BackupVerification) GetResult() VerificationResult {
	if x != nil {
		return x.Result
	}
	return VerificationResult_VERIFICATION_RESULT_UNSPECIFIED
}

func (x *BackupVerification) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BackupVerification) GetTargetContainer() string {
	if x != nil {
		return x.TargetContainer
	}
	return ""
}

func (x *BackupVerification) GetScratchDatabase() string {
	if x != nil {
		return x.ScratchDatabase
	}
	return ""
}

func (x *BackupVerification) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *BackupVerification) GetVerifiedBy() string {
	if x != nil {
		return x.VerifiedBy
	}
	return ""
}

func (x *BackupVerification) GetChecks() []*VerificationCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

// PgConnection carries the connection parameters pg_dump / pg_restore use
// *inside the container*. Defaults target a per-container local Postgres
// reached over loopback. db_password is never logged and is passed to the
// child process via the PGPASSWORD environment variable, not argv.
type PgConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical database to dump or restore into. For CreateBackup, leave
	// empty to back up EVERY non-template database in the container (#954)
	// — the default, no-guessing path; a caller doesn't need to already
	// know a database name, and there's no name left to typo. Set an
	// explicit name to dump just that one database instead. For
	// RestoreBackup, empty means "the backup record's own database"
	// (restore in place) — always required in practice there since a
	// record always names exactly one database.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Postgres role. Defaults to "postgres" when empty.
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// Password for the role. Optional (empty for trust/peer auth or when a
	// PGPASSFILE is configured in the container). Never logged.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// Host as seen from *inside* the container. Defaults to "127.0.0.1".
	Host string `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	// Port. Defaults to 5432 when zero.
	Port          int32 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgConnection) Reset() {
	*x = PgConnection{}
	mi := &file_containarium_v1_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgConnection) ProtoMessage() {}

func (x *PgConnection) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgConnection.ProtoReflect.Descriptor instead.
func (*PgConnection) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{3}
}

func (x *PgConnection) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *PgConnection) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PgConnection) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PgConnection) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PgConnection) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// CreateBackupRequest dumps a container's database and stores it at the
// chosen destination.
type CreateBackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant (username) whose container holds the database.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Connection parameters for pg_dump inside the container. Leave
	// connection.database empty to back up every non-template database
	// found (#954, the default); set it to back up just that one.
	Connection *PgConnection `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// Where to store the dump.
	Destination BackupDestination `protobuf:"varint,3,opt,name=destination,proto3,enum=containarium.v1.BackupDestination" json:"destination,omitempty"`
	// For GCS: the destination bucket/prefix, e.g. "gs://my-backups/pg".
	// Ignored for LOCAL. The object key is appended as "<id>.dump".
	GcsBucket     string `protobuf:"bytes,4,opt,name=gcs_bucket,json=gcsBucket,proto3" json:"gcs_bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBackupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateBackupRequest) GetConnection() *PgConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *CreateBackupRequest) GetDestination() BackupDestination {
	if x != nil {
		return x.Destination
	}
	return BackupDestination_BACKUP_DESTINATION_UNSPECIFIED
}

func (x *CreateBackupRequest) GetGcsBucket() string {
	if x != nil {
		return x.GcsBucket
	}
	return ""
}

type CreateBackupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator-facing summary.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The committed backup record. Populated only when connection.database
	// named exactly one database (single-database create, back-compat
	// shape). For a "back up all" create (connection.database empty),
	// this is unset — use records instead.
	Record *BackupRecord `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	// Every committed backup record from this call. Always populated:
	// one entry for a single-database create (mirrors record above), or
	// one entry per database for a "back up all" create (#954).
	Records []*BackupRecord `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	// Per-database failures from a "back up all" create — a database that
	// failed to dump (e.g. transient pg_dump error) does not abort the
	// others; its failure is reported here instead. Always empty for a
	// single-database create (that path fails the whole RPC on error, as
	// before).
	Failures      []string `protobuf:"bytes,4,rep,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupResponse) Reset() {
	*x = CreateBackupResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupResponse) ProtoMessage() {}

func (x *CreateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBackupResponse) GetRecord() *BackupRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *CreateBackupResponse) GetRecords() []*BackupRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *CreateBackupResponse) GetFailures() []string {
	if x != nil {
		return x.Failures
	}
	return nil
}

// ListBackupsRequest enumerates stored backups, newest first.
type ListBackupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional tenant filter. Empty lists backups for all tenants
	// (admin view).
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{6}
}

func (x *ListBackupsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListBackupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*BackupRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsResponse) Reset() {
	*x = ListBackupsResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResponse) ProtoMessage() {}

func (x *ListBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{7}
}

func (x *ListBackupsResponse) GetRecords() []*BackupRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// GetBackupRequest fetches a single backup record by ID.
type GetBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupRequest) Reset() {
	*x = GetBackupRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupRequest) ProtoMessage() {}

func (x *GetBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupRequest.ProtoReflect.Descriptor instead.
func (*GetBackupRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{8}
}

func (x *GetBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *BackupRecord          `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupResponse) Reset() {
	*x = GetBackupResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupResponse) ProtoMessage() {}

func (x *GetBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupResponse.ProtoReflect.Descriptor instead.
func (*GetBackupResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{9}
}

func (x *GetBackupResponse) GetRecord() *BackupRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

// RestoreBackupRequest streams a stored dump back into a container's
// database via pg_restore. Destructive: with `clean` set it drops and
// recreates objects before loading.
type RestoreBackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backup to restore.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Connection parameters for pg_restore inside the target container.
	// If connection.database is empty, the backup record's database is
	// used (restore in place).
	Connection *PgConnection `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// Pass --clean --if-exists to pg_restore (drop objects before
	// recreating). Off by default so a restore into a fresh database
	// does not error on missing objects.
	Clean         bool `protobuf:"varint,3,opt,name=clean,proto3" json:"clean,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupRequest) Reset() {
	*x = RestoreBackupRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupRequest) ProtoMessage() {}

func (x *RestoreBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreBackupRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{10}
}

func (x *RestoreBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestoreBackupRequest) GetConnection() *PgConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *RestoreBackupRequest) GetClean() bool {
	if x != nil {
		return x.Clean
	}
	return false
}

type RestoreBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupResponse) Reset() {
	*x = RestoreBackupResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupResponse) ProtoMessage() {}

func (x *RestoreBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupResponse.ProtoReflect.Descriptor instead.
func (*RestoreBackupResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{11}
}

func (x *RestoreBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// VerifyBackupRequest restore-tests a stored dump: it loads the dump into
// a throwaway database inside a *target* container and runs
// engine-appropriate sanity checks, then drops the scratch database.
//
// The target is always a container other than the one the backup came
// from — verification must never touch the source database. Supply a
// disposable container as the target; the daemon rejects a request whose
// target resolves to the source container.
type VerifyBackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backup to verify.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant whose container is used as the throwaway restore target.
	// Required, and must differ from the backup's own tenant container.
	TargetUsername string `protobuf:"bytes,2,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	// Connection parameters for the *target* container's Postgres. The
	// scratch database name is generated by the daemon, so
	// connection.database is ignored here.
	Connection    *PgConnection `protobuf:"bytes,3,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBackupRequest) Reset() {
	*x = VerifyBackupRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBackupRequest) ProtoMessage() {}

func (x *VerifyBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBackupRequest.ProtoReflect.Descriptor instead.
func (*VerifyBackupRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyBackupRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

func (x *VerifyBackupRequest) GetConnection() *PgConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type VerifyBackupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator-facing summary, e.g. "verification passed: <id>".
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The verification artifact, including per-check detail and the
	// engine's own error on failure.
	Verification *BackupVerification `protobuf:"bytes,2,opt,name=verification,proto3" json:"verification,omitempty"`
	// The backup record with last_verification updated.
	Record        *BackupRecord `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBackupResponse) Reset() {
	*x = VerifyBackupResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBackupResponse) ProtoMessage() {}

func (x *VerifyBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBackupResponse.ProtoReflect.Descriptor instead.
func (*VerifyBackupResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyBackupResponse) GetVerification() *BackupVerification {
	if x != nil {
		return x.Verification
	}
	return nil
}

func (x *VerifyBackupResponse) GetRecord() *BackupRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

// DeleteBackupRequest removes a stored dump and its index entry.
type DeleteBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupResponse) Reset() {
	*x = DeleteBackupResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupResponse) ProtoMessage() {}

func (x *DeleteBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_containarium_v1_backup_proto protoreflect.FileDescriptor

const file_containarium_v1_backup_proto_rawDesc = "" +
	"\n" +
	"\x1ccontainarium/v1/backup.proto\x12\x0fcontainarium.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb7\x03\n" +
	"\fBackupRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12D\n" +
	"\vdestination\x18\a \x01(\x0e2\".containarium.v1.BackupDestinationR\vdestination\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x16\n" +
	"\x06engine\x18\t \x01(\tR\x06engine\x12P\n" +
	"\x11last_verification\x18\n" +
	" \x01(\v2#.containarium.v1.BackupVerificationR\x10lastVerification\x12*\n" +
	"\x0erelation_count\x18\v \x01(\x03H\x00R\rrelationCount\x88\x01\x01B\x11\n" +
	"\x0f_relation_count\"W\n" +
	"\x11VerificationCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xdc\x02\n" +
	"\x12BackupVerification\x12\x1f\n" +
	"\vverified_at\x18\x01 \x01(\tR\n" +
	"verifiedAt\x12;\n" +
	"\x06result\x18\x02 \x01(\x0e2#.containarium.v1.VerificationResultR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12)\n" +
	"\x10target_container\x18\x04 \x01(\tR\x0ftargetContainer\x12)\n" +
	"\x10scratch_database\x18\x05 \x01(\tR\x0fscratchDatabase\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x1f\n" +
	"\vverified_by\x18\a \x01(\tR\n" +
	"verifiedBy\x12:\n" +
	"\x06checks\x18\b \x03(\v2\".containarium.v1.VerificationCheckR\x06checks\"\x82\x01\n" +
	"\fPgConnection\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\"\xd5\x01\n" +
	"\x13CreateBackupRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12=\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2\x1d.containarium.v1.PgConnectionR\n" +
	"connection\x12D\n" +
	"\vdestination\x18\x03 \x01(\x0e2\".containarium.v1.BackupDestinationR\vdestination\x12\x1d\n" +
	"\n" +
	"gcs_bucket\x18\x04 \x01(\tR\tgcsBucket\"\xbc\x01\n" +
	"\x14CreateBackupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x125\n" +
	"\x06record\x18\x02 \x01(\v2\x1d.containarium.v1.BackupRecordR\x06record\x127\n" +
	"\arecords\x18\x03 \x03(\v2\x1d.containarium.v1.BackupRecordR\arecords\x12\x1a\n" +
	"\bfailures\x18\x04 \x03(\tR\bfailures\"0\n" +
	"\x12ListBackupsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"N\n" +
	"\x13ListBackupsResponse\x127\n" +
	"\arecords\x18\x01 \x03(\v2\x1d.containarium.v1.BackupRecordR\arecords\"\"\n" +
	"\x10GetBackupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x11GetBackupResponse\x125\n" +
	"\x06record\x18\x01 \x01(\v2\x1d.containarium.v1.BackupRecordR\x06record\"{\n" +
	"\x14RestoreBackupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2\x1d.containarium.v1.PgConnectionR\n" +
	"connection\x12\x14\n" +
	"\x05clean\x18\x03 \x01(\bR\x05clean\"1\n" +
	"\x15RestoreBackupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8d\x01\n" +
	"\x13VerifyBackupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0ftarget_username\x18\x02 \x01(\tR\x0etargetUsername\x12=\n" +
	"\n" +
	"connection\x18\x03 \x01(\v2\x1d.containarium.v1.PgConnectionR\n" +
	"connection\"\xb0\x01\n" +
	"\x14VerifyBackupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12G\n" +
	"\fverification\x18\x02 \x01(\v2#.containarium.v1.BackupVerificationR\fverification\x125\n" +
	"\x06record\x18\x03 \x01(\v2\x1d.containarium.v1.BackupRecordR\x06record\"%\n" +
	"\x13DeleteBackupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteBackupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*q\n" +
	"\x11BackupDestination\x12\"\n" +
	"\x1eBACKUP_DESTINATION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18BACKUP_DESTINATION_LOCAL\x10\x01\x12\x1a\n" +
	"\x16BACKUP_DESTINATION_GCS\x10\x02*y\n" +
	"\x12VerificationResult\x12#\n" +
	"\x1fVERIFICATION_RESULT_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aVERIFICATION_RESULT_PASSED\x10\x01\x12\x1e\n" +
	"\x1aVERIFICATION_RESULT_FAILED\x10\x022\xc0\r\n" +
	"\rBackupService\x12\xfb\x02\n" +
	"\fCreateBackup\x12$.containarium.v1.CreateBackupRequest\x1a%.containarium.v1.CreateBackupResponse\"\x9d\x02\x92A\x83\x02\n" +
	"\aBackups\x12\x0fCreate a backup\x1a\xe6\x01Runs pg_dump inside the tenant's container and stores the dump at the chosen off-host destination (local backup dir or GCS). Leave connection.database empty to back up every non-template database found; set it to back up just one.\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/backups\x12\xd3\x01\n" +
	"\vListBackups\x12#.containarium.v1.ListBackupsRequest\x1a$.containarium.v1.ListBackupsResponse\"y\x92Ac\n" +
	"\aBackups\x12\fList backups\x1aJLists stored backup records (newest first), optionally filtered by tenant.\x82\xd3\xe4\x93\x02\r\x12\v/v1/backups\x12\xb8\x01\n" +
	"\tGetBackup\x12!.containarium.v1.GetBackupRequest\x1a\".containarium.v1.GetBackupResponse\"d\x92AI\n" +
	"\aBackups\x12\fGet a backup\x1a0Returns the metadata for a single stored backup.\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/backups/{id}\x12\x88\x02\n" +
	"\rRestoreBackup\x12%.containarium.v1.RestoreBackupRequest\x1a&.containarium.v1.RestoreBackupResponse\"\xa7\x01\x92A\x80\x01\n" +
	"\aBackups\x12\x10Restore a backup\x1acStreams a stored dump back into a container's database via pg_restore. Destructive when clean=true.\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/backups/{id}/restore\x12\x9f\x03\n" +
	"\fVerifyBackup\x12$.containarium.v1.VerifyBackupRequest\x1a%.containarium.v1.VerifyBackupResponse\"\xc1\x02\x92A\x9b\x02\n" +
	"\aBackups\x12\x0fVerify a backup\x1a\xfe\x01Restore-tests a stored dump by loading it into a throwaway database inside a target container and running sanity checks, then dropping the scratch database. Never touches the source container. Records the outcome on the backup as durable A.8.13 evidence.\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/backups/{id}/verify\x12\xf2\x01\n" +
	"\fDeleteBackup\x12$.containarium.v1.DeleteBackupRequest\x1a%.containarium.v1.DeleteBackupResponse\"\x94\x01\x92Ay\n" +
	"\aBackups\x12\x0fDelete a backup\x1a]Deletes a stored dump and its metadata. Retention enforcement is the caller's responsibility.\x82\xd3\xe4\x93\x02\x12*\x10/v1/backups/{id}BKZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var (
	file_containarium_v1_backup_proto_rawDescOnce sync.Once
	file_containarium_v1_backup_proto_rawDescData []byte
)

func file_containarium_v1_backup_proto_rawDescGZIP() []byte {
	file_containarium_v1_backup_proto_rawDescOnce.Do(func() {
		file_containarium_v1_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containarium_v1_backup_proto_rawDesc), len(file_containarium_v1_backup_proto_rawDesc)))
	})
	return file_containarium_v1_backup_proto_rawDescData
}

var file_containarium_v1_backup_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_containarium_v1_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_containarium_v1_backup_proto_goTypes = []any{
	(BackupDestination)(0),        // 0: containarium.v1.BackupDestination
	(VerificationResult)(0),       // 1: containarium.v1.VerificationResult
	(*BackupRecord)(nil),          // 2: containarium.v1.BackupRecord
	(*VerificationCheck)(nil),     // 3: containarium.v1.VerificationCheck
	(*BackupVerification)(nil),    // 4: containarium.v1.BackupVerification
	(*PgConnection)(nil),          // 5: containarium.v1.PgConnection
	(*CreateBackupRequest)(nil),   // 6: containarium.v1.CreateBackupRequest
	(*CreateBackupResponse)(nil),  // 7: containarium.v1.CreateBackupResponse
	(*ListBackupsRequest)(nil),    // 8: containarium.v1.ListBackupsRequest
	(*ListBackupsResponse)(nil),   // 9: containarium.v1.ListBackupsResponse
	(*GetBackupRequest)(nil),      // 10: containarium.v1.GetBackupRequest
	(*GetBackupResponse)(nil),     // 11: containarium.v1.GetBackupResponse
	(*RestoreBackupRequest)(nil),  // 12: containarium.v1.RestoreBackupRequest
	(*RestoreBackupResponse)(nil), // 13: containarium.v1.RestoreBackupResponse
	(*VerifyBackupRequest)(nil),   // 14: containarium.v1.VerifyBackupRequest
	(*VerifyBackupResponse)(nil),  // 15: containarium.v1.VerifyBackupResponse
	(*DeleteBackupRequest)(nil),   // 16: containarium.v1.DeleteBackupRequest
	(*DeleteBackupResponse)(nil),  // 17: containarium.v1.DeleteBackupResponse
}
var file_containarium_v1_backup_proto_depIdxs = []int32{
	0,  // 0: containarium.v1.BackupRecord.destination:type_name -> containarium.v1.BackupDestination
	4,  // 1: containarium.v1.BackupRecord.last_verification:type_name -> containarium.v1.BackupVerification
	1,  // 2: containarium.v1.BackupVerification.result:type_name -> containarium.v1.VerificationResult
	3,  // 3: containarium.v1.BackupVerification.checks:type_name -> containarium.v1.VerificationCheck
	5,  // 4: containarium.v1.CreateBackupRequest.connection:type_name -> containarium.v1.PgConnection
	0,  // 5: containarium.v1.CreateBackupRequest.destination:type_name -> containarium.v1.BackupDestination
	2,  // 6: containarium.v1.CreateBackupResponse.record:type_name -> containarium.v1.BackupRecord
	2,  // 7: containarium.v1.CreateBackupResponse.records:type_name -> containarium.v1.BackupRecord
	2,  // 8: containarium.v1.ListBackupsResponse.records:type_name -> containarium.v1.BackupRecord
	2,  // 9: containarium.v1.GetBackupResponse.record:type_name -> containarium.v1.BackupRecord
	5,  // 10: containarium.v1.RestoreBackupRequest.connection:type_name -> containarium.v1.PgConnection
	5,  // 11: containarium.v1.VerifyBackupRequest.connection:type_name -> containarium.v1.PgConnection
	4,  // 12: containarium.v1.VerifyBackupResponse.verification:type_name -> containarium.v1.BackupVerification
	2,  // 13: containarium.v1.VerifyBackupResponse.record:type_name -> containarium.v1.BackupRecord
	6,  // 14: containarium.v1.BackupService.CreateBackup:input_type -> containarium.v1.CreateBackupRequest
	8,  // 15: containarium.v1.BackupService.ListBackups:input_type -> containarium.v1.ListBackupsRequest
	10, // 16: containarium.v1.BackupService.GetBackup:input_type -> containarium.v1.GetBackupRequest
	12, // 17: containarium.v1.BackupService.RestoreBackup:input_type -> containarium.v1.RestoreBackupRequest
	14, // 18: containarium.v1.BackupService.VerifyBackup:input_type -> containarium.v1.VerifyBackupRequest
	16, // 19: containarium.v1.BackupService.DeleteBackup:input_type -> containarium.v1.DeleteBackupRequest
	7,  // 20: containarium.v1.BackupService.CreateBackup:output_type -> containarium.v1.CreateBackupResponse
	9,  // 21: containarium.v1.BackupService.ListBackups:output_type -> containarium.v1.ListBackupsResponse
	11, // 22: containarium.v1.BackupService.GetBackup:output_type -> containarium.v1.GetBackupResponse
	13, // 23: containarium.v1.BackupService.RestoreBackup:output_type -> containarium.v1.RestoreBackupResponse
	15, // 24: containarium.v1.BackupService.VerifyBackup:output_type -> containarium.v1.VerifyBackupResponse
	17, // 25: containarium.v1.BackupService.DeleteBackup:output_type -> containarium.v1.DeleteBackupResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_containarium_v1_backup_proto_init() }
func file_containarium_v1_backup_proto_init() {
	if File_containarium_v1_backup_proto != nil {
		return
	}
	file_containarium_v1_backup_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_backup_proto_rawDesc), len(file_containarium_v1_backup_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containarium_v1_backup_proto_goTypes,
		DependencyIndexes: file_containarium_v1_backup_proto_depIdxs,
		EnumInfos:         file_containarium_v1_backup_proto_enumTypes,
		MessageInfos:      file_containarium_v1_backup_proto_msgTypes,
	}.Build()
	File_containarium_v1_backup_proto = out.File
	file_containarium_v1_backup_proto_goTypes = nil
	file_containarium_v1_backup_proto_depIdxs = nil
}
