// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: containarium/v1/code_egress.proto

/*
Package containariumv1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package containariumv1

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_0(ctx context.Context, marshaler runtime.Marshaler, client CodingToolEgressPolicyServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq SetCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq.Policy); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	val, ok := pathParams["policy.tenant"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "policy.tenant")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "policy.tenant", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "policy.tenant", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.SetCodingToolEgressPolicy(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_0(ctx context.Context, marshaler runtime.Marshaler, server CodingToolEgressPolicyServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq SetCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq.Policy); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	val, ok := pathParams["policy.tenant"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "policy.tenant")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "policy.tenant", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "policy.tenant", err)
	}
	msg, err := server.SetCodingToolEgressPolicy(ctx, &protoReq)
	return msg, metadata, err
}

func request_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_1(ctx context.Context, marshaler runtime.Marshaler, client CodingToolEgressPolicyServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq SetCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq.Policy); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.SetCodingToolEgressPolicy(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_1(ctx context.Context, marshaler runtime.Marshaler, server CodingToolEgressPolicyServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq SetCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq.Policy); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.SetCodingToolEgressPolicy(ctx, &protoReq)
	return msg, metadata, err
}

func request_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_0(ctx context.Context, marshaler runtime.Marshaler, client CodingToolEgressPolicyServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["tenant"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "tenant")
	}
	protoReq.Tenant, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "tenant", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.GetCodingToolEgressPolicy(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_0(ctx context.Context, marshaler runtime.Marshaler, server CodingToolEgressPolicyServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["tenant"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "tenant")
	}
	protoReq.Tenant, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "tenant", err)
	}
	msg, err := server.GetCodingToolEgressPolicy(ctx, &protoReq)
	return msg, metadata, err
}

var filter_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}

func request_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1(ctx context.Context, marshaler runtime.Marshaler, client CodingToolEgressPolicyServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
	)
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.GetCodingToolEgressPolicy(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1(ctx context.Context, marshaler runtime.Marshaler, server CodingToolEgressPolicyServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
	)
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetCodingToolEgressPolicy(ctx, &protoReq)
	return msg, metadata, err
}

func request_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_0(ctx context.Context, marshaler runtime.Marshaler, client CodingToolEgressPolicyServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq DeleteCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["tenant"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "tenant")
	}
	protoReq.Tenant, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "tenant", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.DeleteCodingToolEgressPolicy(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_0(ctx context.Context, marshaler runtime.Marshaler, server CodingToolEgressPolicyServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq DeleteCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["tenant"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "tenant")
	}
	protoReq.Tenant, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "tenant", err)
	}
	msg, err := server.DeleteCodingToolEgressPolicy(ctx, &protoReq)
	return msg, metadata, err
}

var filter_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}

func request_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1(ctx context.Context, marshaler runtime.Marshaler, client CodingToolEgressPolicyServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq DeleteCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
	)
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.DeleteCodingToolEgressPolicy(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1(ctx context.Context, marshaler runtime.Marshaler, server CodingToolEgressPolicyServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq DeleteCodingToolEgressPolicyRequest
		metadata runtime.ServerMetadata
	)
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.DeleteCodingToolEgressPolicy(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterCodingToolEgressPolicyServiceHandlerServer registers the http handlers for service CodingToolEgressPolicyService to "mux".
// UnaryRPC     :call CodingToolEgressPolicyServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterCodingToolEgressPolicyServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterCodingToolEgressPolicyServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server CodingToolEgressPolicyServiceServer) error {
	mux.Handle(http.MethodPut, pattern_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/SetCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy/{policy.tenant}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPut, pattern_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_1, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/SetCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_1(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_1(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/GetCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy/{tenant}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/GetCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodDelete, pattern_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/DeleteCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy/{tenant}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodDelete, pattern_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/DeleteCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterCodingToolEgressPolicyServiceHandlerFromEndpoint is same as RegisterCodingToolEgressPolicyServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterCodingToolEgressPolicyServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterCodingToolEgressPolicyServiceHandler(ctx, mux, conn)
}

// RegisterCodingToolEgressPolicyServiceHandler registers the http handlers for service CodingToolEgressPolicyService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterCodingToolEgressPolicyServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterCodingToolEgressPolicyServiceHandlerClient(ctx, mux, NewCodingToolEgressPolicyServiceClient(conn))
}

// RegisterCodingToolEgressPolicyServiceHandlerClient registers the http handlers for service CodingToolEgressPolicyService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "CodingToolEgressPolicyServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "CodingToolEgressPolicyServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "CodingToolEgressPolicyServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterCodingToolEgressPolicyServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client CodingToolEgressPolicyServiceClient) error {
	mux.Handle(http.MethodPut, pattern_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/SetCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy/{policy.tenant}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPut, pattern_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_1, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/SetCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_1(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_1(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/GetCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy/{tenant}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/GetCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodDelete, pattern_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/DeleteCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy/{tenant}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodDelete, pattern_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/containarium.v1.CodingToolEgressPolicyService/DeleteCodingToolEgressPolicy", runtime.WithHTTPPathPattern("/v1/code/egress-policy"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_0    = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3}, []string{"v1", "code", "egress-policy", "policy.tenant"}, ""))
	pattern_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_1    = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v1", "code", "egress-policy"}, ""))
	pattern_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_0    = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3}, []string{"v1", "code", "egress-policy", "tenant"}, ""))
	pattern_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1    = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v1", "code", "egress-policy"}, ""))
	pattern_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3}, []string{"v1", "code", "egress-policy", "tenant"}, ""))
	pattern_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v1", "code", "egress-policy"}, ""))
)

var (
	forward_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_0    = runtime.ForwardResponseMessage
	forward_CodingToolEgressPolicyService_SetCodingToolEgressPolicy_1    = runtime.ForwardResponseMessage
	forward_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_0    = runtime.ForwardResponseMessage
	forward_CodingToolEgressPolicyService_GetCodingToolEgressPolicy_1    = runtime.ForwardResponseMessage
	forward_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_0 = runtime.ForwardResponseMessage
	forward_CodingToolEgressPolicyService_DeleteCodingToolEgressPolicy_1 = runtime.ForwardResponseMessage
)
