// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: containarium/v1/sandbox.proto

package containariumv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxService_SpawnSandbox_FullMethodName       = "/containarium.v1.SandboxService/SpawnSandbox"
	SandboxService_ExecInSandbox_FullMethodName      = "/containarium.v1.SandboxService/ExecInSandbox"
	SandboxService_WriteFileInSandbox_FullMethodName = "/containarium.v1.SandboxService/WriteFileInSandbox"
	SandboxService_ReadFileInSandbox_FullMethodName  = "/containarium.v1.SandboxService/ReadFileInSandbox"
	SandboxService_DeleteSandbox_FullMethodName      = "/containarium.v1.SandboxService/DeleteSandbox"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxService is the two-digit-ms spawn path
// (docs/architecture/two-digit-ms-sandbox-spawn.md): an isolated Linux
// process for an agent inner loop, claimed against a pool rather than
// created fresh per request.
//
// A sandbox is NOT a persistent box. It has no per-tenant Linux account and
// no SSH — access is exclusively these RPCs, over a connection the daemon
// already holds open. That is the scope cut that makes the latency target
// reachable (see the design note's "What's in it" section); a caller that
// needs `ssh <user>@box` wants ContainerService instead.
//
// Phase 1 (this contract's first implementation) is the cold path only —
// every SpawnSandbox call creates a fresh container, same floor as
// ContainerService.CreateContainer minus identity seeding. served_from is
// always COLD until Phase 3 adds the warm pool; the field exists now so
// that Phase 3 is not a breaking proto change.
type SandboxServiceClient interface {
	// SpawnSandbox creates (Phase 1) or claims (Phase 3+) a sandbox and
	// returns as soon as it can accept ExecInSandbox — the two-digit-ms path.
	SpawnSandbox(ctx context.Context, in *SpawnSandboxRequest, opts ...grpc.CallOption) (*SpawnSandboxResponse, error)
	// ExecInSandbox runs one command inside the sandbox and returns its
	// output. The sandbox's only access surface — there is no SSH.
	ExecInSandbox(ctx context.Context, in *ExecInSandboxRequest, opts ...grpc.CallOption) (*ExecInSandboxResponse, error)
	// WriteFileInSandbox writes a file into the sandbox via the Incus file
	// push API — never through a shell, so file content can never be
	// interpreted as a command.
	WriteFileInSandbox(ctx context.Context, in *WriteFileInSandboxRequest, opts ...grpc.CallOption) (*WriteFileInSandboxResponse, error)
	// ReadFileInSandbox reads a file back out of the sandbox.
	ReadFileInSandbox(ctx context.Context, in *ReadFileInSandboxRequest, opts ...grpc.CallOption) (*ReadFileInSandboxResponse, error)
	// DeleteSandbox destroys the sandbox immediately. Sandboxes are never
	// reset and reused (see the design note's Isolation section) — delete
	// always means destroy, never "return to a pool".
	DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*DeleteSandboxResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) SpawnSandbox(ctx context.Context, in *SpawnSandboxRequest, opts ...grpc.CallOption) (*SpawnSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_SpawnSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ExecInSandbox(ctx context.Context, in *ExecInSandboxRequest, opts ...grpc.CallOption) (*ExecInSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecInSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_ExecInSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) WriteFileInSandbox(ctx context.Context, in *WriteFileInSandboxRequest, opts ...grpc.CallOption) (*WriteFileInSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileInSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_WriteFileInSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ReadFileInSandbox(ctx context.Context, in *ReadFileInSandboxRequest, opts ...grpc.CallOption) (*ReadFileInSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileInSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_ReadFileInSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*DeleteSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_DeleteSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
//
// SandboxService is the two-digit-ms spawn path
// (docs/architecture/two-digit-ms-sandbox-spawn.md): an isolated Linux
// process for an agent inner loop, claimed against a pool rather than
// created fresh per request.
//
// A sandbox is NOT a persistent box. It has no per-tenant Linux account and
// no SSH — access is exclusively these RPCs, over a connection the daemon
// already holds open. That is the scope cut that makes the latency target
// reachable (see the design note's "What's in it" section); a caller that
// needs `ssh <user>@box` wants ContainerService instead.
//
// Phase 1 (this contract's first implementation) is the cold path only —
// every SpawnSandbox call creates a fresh container, same floor as
// ContainerService.CreateContainer minus identity seeding. served_from is
// always COLD until Phase 3 adds the warm pool; the field exists now so
// that Phase 3 is not a breaking proto change.
type SandboxServiceServer interface {
	// SpawnSandbox creates (Phase 1) or claims (Phase 3+) a sandbox and
	// returns as soon as it can accept ExecInSandbox — the two-digit-ms path.
	SpawnSandbox(context.Context, *SpawnSandboxRequest) (*SpawnSandboxResponse, error)
	// ExecInSandbox runs one command inside the sandbox and returns its
	// output. The sandbox's only access surface — there is no SSH.
	ExecInSandbox(context.Context, *ExecInSandboxRequest) (*ExecInSandboxResponse, error)
	// WriteFileInSandbox writes a file into the sandbox via the Incus file
	// push API — never through a shell, so file content can never be
	// interpreted as a command.
	WriteFileInSandbox(context.Context, *WriteFileInSandboxRequest) (*WriteFileInSandboxResponse, error)
	// ReadFileInSandbox reads a file back out of the sandbox.
	ReadFileInSandbox(context.Context, *ReadFileInSandboxRequest) (*ReadFileInSandboxResponse, error)
	// DeleteSandbox destroys the sandbox immediately. Sandboxes are never
	// reset and reused (see the design note's Isolation section) — delete
	// always means destroy, never "return to a pool".
	DeleteSandbox(context.Context, *DeleteSandboxRequest) (*DeleteSandboxResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) SpawnSandbox(context.Context, *SpawnSandboxRequest) (*SpawnSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpawnSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) ExecInSandbox(context.Context, *ExecInSandboxRequest) (*ExecInSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecInSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) WriteFileInSandbox(context.Context, *WriteFileInSandboxRequest) (*WriteFileInSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFileInSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) ReadFileInSandbox(context.Context, *ReadFileInSandboxRequest) (*ReadFileInSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFileInSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) DeleteSandbox(context.Context, *DeleteSandboxRequest) (*DeleteSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_SpawnSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SpawnSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SpawnSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SpawnSandbox(ctx, req.(*SpawnSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ExecInSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecInSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ExecInSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ExecInSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ExecInSandbox(ctx, req.(*ExecInSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_WriteFileInSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileInSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).WriteFileInSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_WriteFileInSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).WriteFileInSandbox(ctx, req.(*WriteFileInSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ReadFileInSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileInSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ReadFileInSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ReadFileInSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ReadFileInSandbox(ctx, req.(*ReadFileInSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DeleteSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DeleteSandbox(ctx, req.(*DeleteSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containarium.v1.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpawnSandbox",
			Handler:    _SandboxService_SpawnSandbox_Handler,
		},
		{
			MethodName: "ExecInSandbox",
			Handler:    _SandboxService_ExecInSandbox_Handler,
		},
		{
			MethodName: "WriteFileInSandbox",
			Handler:    _SandboxService_WriteFileInSandbox_Handler,
		},
		{
			MethodName: "ReadFileInSandbox",
			Handler:    _SandboxService_ReadFileInSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _SandboxService_DeleteSandbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "containarium/v1/sandbox.proto",
}

const (
	SpawnService_Spawn_FullMethodName = "/containarium.v1.SpawnService/Spawn"
	SpawnService_Exec_FullMethodName  = "/containarium.v1.SpawnService/Exec"
)

// SpawnServiceClient is the client API for SpawnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpawnService is agent-box's resident, low-latency counterpart to
// SandboxService's per-call Incus round-trips (#1488 Phase 2). Each Incus
// exec websocket-upgrades at ~50-150ms; a warm gRPC connection straight to
// the box does the same work in ~3ms. The daemon reaches this over a
// bind-mounted unix socket (see the design note's "Transport" section),
// never over the network.
//
// This is deliberately the only service in this package with NO
// google.api.http annotations: it is not part of the public API surface —
// SandboxService is what external callers (CLI, MCP, SDK) talk to, and its
// implementation is what will route through SpawnService once a warm pool
// exists (Phase 3). Nothing here is reachable through the REST gateway,
// and it must not be registered there.
//
// agent-box runs as PID 1 inside a pool member (see the design note's flow
// diagram), so it owns reaping every process it forks — a design this
// service inherits from the existing process_start/shell_exec MCP tools in
// internal/agentbox, not a new mechanism.
type SpawnServiceClient interface {
	// Spawn starts a long-running background process and returns immediately
	// with its pid. The process is reaped (waited on), never left a zombie,
	// when it exits.
	Spawn(ctx context.Context, in *SpawnRequest, opts ...grpc.CallOption) (*SpawnResponse, error)
	// Exec runs one command to completion and returns its stdout, stderr,
	// and exit code — the fast-path equivalent of
	// SandboxService.ExecInSandbox, minus the Incus round-trip.
	Exec(ctx context.Context, in *AgentExecRequest, opts ...grpc.CallOption) (*AgentExecResponse, error)
}

type spawnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpawnServiceClient(cc grpc.ClientConnInterface) SpawnServiceClient {
	return &spawnServiceClient{cc}
}

func (c *spawnServiceClient) Spawn(ctx context.Context, in *SpawnRequest, opts ...grpc.CallOption) (*SpawnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnResponse)
	err := c.cc.Invoke(ctx, SpawnService_Spawn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spawnServiceClient) Exec(ctx context.Context, in *AgentExecRequest, opts ...grpc.CallOption) (*AgentExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentExecResponse)
	err := c.cc.Invoke(ctx, SpawnService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpawnServiceServer is the server API for SpawnService service.
// All implementations must embed UnimplementedSpawnServiceServer
// for forward compatibility.
//
// SpawnService is agent-box's resident, low-latency counterpart to
// SandboxService's per-call Incus round-trips (#1488 Phase 2). Each Incus
// exec websocket-upgrades at ~50-150ms; a warm gRPC connection straight to
// the box does the same work in ~3ms. The daemon reaches this over a
// bind-mounted unix socket (see the design note's "Transport" section),
// never over the network.
//
// This is deliberately the only service in this package with NO
// google.api.http annotations: it is not part of the public API surface —
// SandboxService is what external callers (CLI, MCP, SDK) talk to, and its
// implementation is what will route through SpawnService once a warm pool
// exists (Phase 3). Nothing here is reachable through the REST gateway,
// and it must not be registered there.
//
// agent-box runs as PID 1 inside a pool member (see the design note's flow
// diagram), so it owns reaping every process it forks — a design this
// service inherits from the existing process_start/shell_exec MCP tools in
// internal/agentbox, not a new mechanism.
type SpawnServiceServer interface {
	// Spawn starts a long-running background process and returns immediately
	// with its pid. The process is reaped (waited on), never left a zombie,
	// when it exits.
	Spawn(context.Context, *SpawnRequest) (*SpawnResponse, error)
	// Exec runs one command to completion and returns its stdout, stderr,
	// and exit code — the fast-path equivalent of
	// SandboxService.ExecInSandbox, minus the Incus round-trip.
	Exec(context.Context, *AgentExecRequest) (*AgentExecResponse, error)
	mustEmbedUnimplementedSpawnServiceServer()
}

// UnimplementedSpawnServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpawnServiceServer struct{}

func (UnimplementedSpawnServiceServer) Spawn(context.Context, *SpawnRequest) (*SpawnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Spawn not implemented")
}
func (UnimplementedSpawnServiceServer) Exec(context.Context, *AgentExecRequest) (*AgentExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSpawnServiceServer) mustEmbedUnimplementedSpawnServiceServer() {}
func (UnimplementedSpawnServiceServer) testEmbeddedByValue()                      {}

// UnsafeSpawnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpawnServiceServer will
// result in compilation errors.
type UnsafeSpawnServiceServer interface {
	mustEmbedUnimplementedSpawnServiceServer()
}

func RegisterSpawnServiceServer(s grpc.ServiceRegistrar, srv SpawnServiceServer) {
	// If the following call panics, it indicates UnimplementedSpawnServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpawnService_ServiceDesc, srv)
}

func _SpawnService_Spawn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpawnServiceServer).Spawn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpawnService_Spawn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpawnServiceServer).Spawn(ctx, req.(*SpawnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpawnService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpawnServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpawnService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpawnServiceServer).Exec(ctx, req.(*AgentExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpawnService_ServiceDesc is the grpc.ServiceDesc for SpawnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpawnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containarium.v1.SpawnService",
	HandlerType: (*SpawnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Spawn",
			Handler:    _SpawnService_Spawn_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _SpawnService_Exec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "containarium/v1/sandbox.proto",
}
