// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: containarium/v1/threatdetection.proto

package containariumv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThreatDetectionService_GetSentryStatus_FullMethodName = "/containarium.v1.ThreatDetectionService/GetSentryStatus"
)

// ThreatDetectionServiceClient is the client API for ThreatDetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ThreatDetectionService serves the background security-sentry's status and
// findings. GetSentryStatus ships with #1640 (background detection loop);
// the findings/rule-config RPCs are added by later stories in the same
// umbrella (#1641-#1643) — see docs/architecture/continuous-threat-detection.md.
type ThreatDetectionServiceClient interface {
	// GetSentryStatus returns the detection engine's on/off state and the
	// health of every registered rule.
	GetSentryStatus(ctx context.Context, in *GetSentryStatusRequest, opts ...grpc.CallOption) (*GetSentryStatusResponse, error)
}

type threatDetectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThreatDetectionServiceClient(cc grpc.ClientConnInterface) ThreatDetectionServiceClient {
	return &threatDetectionServiceClient{cc}
}

func (c *threatDetectionServiceClient) GetSentryStatus(ctx context.Context, in *GetSentryStatusRequest, opts ...grpc.CallOption) (*GetSentryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSentryStatusResponse)
	err := c.cc.Invoke(ctx, ThreatDetectionService_GetSentryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThreatDetectionServiceServer is the server API for ThreatDetectionService service.
// All implementations must embed UnimplementedThreatDetectionServiceServer
// for forward compatibility.
//
// ThreatDetectionService serves the background security-sentry's status and
// findings. GetSentryStatus ships with #1640 (background detection loop);
// the findings/rule-config RPCs are added by later stories in the same
// umbrella (#1641-#1643) — see docs/architecture/continuous-threat-detection.md.
type ThreatDetectionServiceServer interface {
	// GetSentryStatus returns the detection engine's on/off state and the
	// health of every registered rule.
	GetSentryStatus(context.Context, *GetSentryStatusRequest) (*GetSentryStatusResponse, error)
	mustEmbedUnimplementedThreatDetectionServiceServer()
}

// UnimplementedThreatDetectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThreatDetectionServiceServer struct{}

func (UnimplementedThreatDetectionServiceServer) GetSentryStatus(context.Context, *GetSentryStatusRequest) (*GetSentryStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSentryStatus not implemented")
}
func (UnimplementedThreatDetectionServiceServer) mustEmbedUnimplementedThreatDetectionServiceServer() {
}
func (UnimplementedThreatDetectionServiceServer) testEmbeddedByValue() {}

// UnsafeThreatDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThreatDetectionServiceServer will
// result in compilation errors.
type UnsafeThreatDetectionServiceServer interface {
	mustEmbedUnimplementedThreatDetectionServiceServer()
}

func RegisterThreatDetectionServiceServer(s grpc.ServiceRegistrar, srv ThreatDetectionServiceServer) {
	// If the following call panics, it indicates UnimplementedThreatDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThreatDetectionService_ServiceDesc, srv)
}

func _ThreatDetectionService_GetSentryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSentryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatDetectionServiceServer).GetSentryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatDetectionService_GetSentryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatDetectionServiceServer).GetSentryStatus(ctx, req.(*GetSentryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThreatDetectionService_ServiceDesc is the grpc.ServiceDesc for ThreatDetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThreatDetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containarium.v1.ThreatDetectionService",
	HandlerType: (*ThreatDetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSentryStatus",
			Handler:    _ThreatDetectionService_GetSentryStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "containarium/v1/threatdetection.proto",
}
