// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/traffic.proto

package containariumv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Protocol represents the network protocol of a connection
type Protocol int32

const (
	// Unspecified protocol (should not be used)
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	// TCP protocol
	Protocol_PROTOCOL_TCP Protocol = 1
	// UDP protocol
	Protocol_PROTOCOL_UDP Protocol = 2
	// ICMP protocol
	Protocol_PROTOCOL_ICMP Protocol = 3
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_UDP",
		3: "PROTOCOL_ICMP",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_UDP":         2,
		"PROTOCOL_ICMP":        3,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_traffic_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_containarium_v1_traffic_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{0}
}

// ConnectionState represents the state of a TCP connection
type ConnectionState int32

const (
	// Unspecified state
	ConnectionState_CONNECTION_STATE_UNSPECIFIED ConnectionState = 0
	// New connection (SYN sent/received)
	ConnectionState_CONNECTION_STATE_NEW ConnectionState = 1
	// Connection established
	ConnectionState_CONNECTION_STATE_ESTABLISHED ConnectionState = 2
	// Related connection (e.g., FTP data connection)
	ConnectionState_CONNECTION_STATE_RELATED ConnectionState = 3
	// Connection in TIME_WAIT state
	ConnectionState_CONNECTION_STATE_TIME_WAIT ConnectionState = 4
	// Connection in CLOSE_WAIT state
	ConnectionState_CONNECTION_STATE_CLOSE_WAIT ConnectionState = 5
	// Connection in FIN_WAIT state
	ConnectionState_CONNECTION_STATE_FIN_WAIT ConnectionState = 6
	// Connection closed
	ConnectionState_CONNECTION_STATE_CLOSED ConnectionState = 7
	// SYN sent, waiting for response
	ConnectionState_CONNECTION_STATE_SYN_SENT ConnectionState = 8
	// SYN received, waiting for ACK
	ConnectionState_CONNECTION_STATE_SYN_RECV ConnectionState = 9
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "CONNECTION_STATE_UNSPECIFIED",
		1: "CONNECTION_STATE_NEW",
		2: "CONNECTION_STATE_ESTABLISHED",
		3: "CONNECTION_STATE_RELATED",
		4: "CONNECTION_STATE_TIME_WAIT",
		5: "CONNECTION_STATE_CLOSE_WAIT",
		6: "CONNECTION_STATE_FIN_WAIT",
		7: "CONNECTION_STATE_CLOSED",
		8: "CONNECTION_STATE_SYN_SENT",
		9: "CONNECTION_STATE_SYN_RECV",
	}
	ConnectionState_value = map[string]int32{
		"CONNECTION_STATE_UNSPECIFIED": 0,
		"CONNECTION_STATE_NEW":         1,
		"CONNECTION_STATE_ESTABLISHED": 2,
		"CONNECTION_STATE_RELATED":     3,
		"CONNECTION_STATE_TIME_WAIT":   4,
		"CONNECTION_STATE_CLOSE_WAIT":  5,
		"CONNECTION_STATE_FIN_WAIT":    6,
		"CONNECTION_STATE_CLOSED":      7,
		"CONNECTION_STATE_SYN_SENT":    8,
		"CONNECTION_STATE_SYN_RECV":    9,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_traffic_proto_enumTypes[1].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_containarium_v1_traffic_proto_enumTypes[1]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionState.Descriptor instead.
func (ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{1}
}

// TrafficDirection indicates the direction of traffic relative to the container
type TrafficDirection int32

const (
	// Unspecified direction
	TrafficDirection_TRAFFIC_DIRECTION_UNSPECIFIED TrafficDirection = 0
	// Traffic coming into the container
	TrafficDirection_TRAFFIC_DIRECTION_INGRESS TrafficDirection = 1
	// Traffic leaving the container
	TrafficDirection_TRAFFIC_DIRECTION_EGRESS TrafficDirection = 2
)

// Enum value maps for TrafficDirection.
var (
	TrafficDirection_name = map[int32]string{
		0: "TRAFFIC_DIRECTION_UNSPECIFIED",
		1: "TRAFFIC_DIRECTION_INGRESS",
		2: "TRAFFIC_DIRECTION_EGRESS",
	}
	TrafficDirection_value = map[string]int32{
		"TRAFFIC_DIRECTION_UNSPECIFIED": 0,
		"TRAFFIC_DIRECTION_INGRESS":     1,
		"TRAFFIC_DIRECTION_EGRESS":      2,
	}
)

func (x TrafficDirection) Enum() *TrafficDirection {
	p := new(TrafficDirection)
	*p = x
	return p
}

func (x TrafficDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_traffic_proto_enumTypes[2].Descriptor()
}

func (TrafficDirection) Type() protoreflect.EnumType {
	return &file_containarium_v1_traffic_proto_enumTypes[2]
}

func (x TrafficDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficDirection.Descriptor instead.
func (TrafficDirection) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{2}
}

// TrafficEventType represents the type of traffic event
type TrafficEventType int32

const (
	// Unspecified event type
	TrafficEventType_TRAFFIC_EVENT_TYPE_UNSPECIFIED TrafficEventType = 0
	// New connection established
	TrafficEventType_TRAFFIC_EVENT_TYPE_NEW TrafficEventType = 1
	// Connection state or counters updated
	TrafficEventType_TRAFFIC_EVENT_TYPE_UPDATE TrafficEventType = 2
	// Connection terminated
	TrafficEventType_TRAFFIC_EVENT_TYPE_DESTROY TrafficEventType = 3
)

// Enum value maps for TrafficEventType.
var (
	TrafficEventType_name = map[int32]string{
		0: "TRAFFIC_EVENT_TYPE_UNSPECIFIED",
		1: "TRAFFIC_EVENT_TYPE_NEW",
		2: "TRAFFIC_EVENT_TYPE_UPDATE",
		3: "TRAFFIC_EVENT_TYPE_DESTROY",
	}
	TrafficEventType_value = map[string]int32{
		"TRAFFIC_EVENT_TYPE_UNSPECIFIED": 0,
		"TRAFFIC_EVENT_TYPE_NEW":         1,
		"TRAFFIC_EVENT_TYPE_UPDATE":      2,
		"TRAFFIC_EVENT_TYPE_DESTROY":     3,
	}
)

func (x TrafficEventType) Enum() *TrafficEventType {
	p := new(TrafficEventType)
	*p = x
	return p
}

func (x TrafficEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_traffic_proto_enumTypes[3].Descriptor()
}

func (TrafficEventType) Type() protoreflect.EnumType {
	return &file_containarium_v1_traffic_proto_enumTypes[3]
}

func (x TrafficEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficEventType.Descriptor instead.
func (TrafficEventType) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{3}
}

// Connection represents an active or recent network connection
type Connection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique connection ID (from conntrack)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Container name this connection belongs to
	ContainerName string `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Container IP address
	ContainerIp string `protobuf:"bytes,3,opt,name=container_ip,json=containerIp,proto3" json:"container_ip,omitempty"`
	// Protocol (TCP, UDP, ICMP)
	Protocol Protocol `protobuf:"varint,4,opt,name=protocol,proto3,enum=containarium.v1.Protocol" json:"protocol,omitempty"`
	// Source IP address
	SourceIp string `protobuf:"bytes,5,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// Source port (0 for ICMP)
	SourcePort uint32 `protobuf:"varint,6,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// Destination IP address
	DestIp string `protobuf:"bytes,7,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	// Destination port (0 for ICMP)
	DestPort uint32 `protobuf:"varint,8,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	// Connection state (primarily for TCP)
	State ConnectionState `protobuf:"varint,9,opt,name=state,proto3,enum=containarium.v1.ConnectionState" json:"state,omitempty"`
	// Direction relative to the container
	Direction TrafficDirection `protobuf:"varint,10,opt,name=direction,proto3,enum=containarium.v1.TrafficDirection" json:"direction,omitempty"`
	// Bytes sent from the container
	BytesSent int64 `protobuf:"varint,11,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	// Bytes received by the container
	BytesReceived int64 `protobuf:"varint,12,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	// Packets sent from the container
	PacketsSent int64 `protobuf:"varint,13,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	// Packets received by the container
	PacketsReceived int64 `protobuf:"varint,14,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	// When the connection was first seen
	FirstSeen *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	// When the connection was last active
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// TTL remaining in conntrack (seconds)
	TimeoutSeconds int32 `protobuf:"varint,17,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{0}
}

func (x *Connection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Connection) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Connection) GetContainerIp() string {
	if x != nil {
		return x.ContainerIp
	}
	return ""
}

func (x *Connection) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *Connection) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *Connection) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *Connection) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *Connection) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *Connection) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_CONNECTION_STATE_UNSPECIFIED
}

func (x *Connection) GetDirection() TrafficDirection {
	if x != nil {
		return x.Direction
	}
	return TrafficDirection_TRAFFIC_DIRECTION_UNSPECIFIED
}

func (x *Connection) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *Connection) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *Connection) GetPacketsSent() int64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *Connection) GetPacketsReceived() int64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *Connection) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Connection) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Connection) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// TrafficEvent represents a real-time connection event
type TrafficEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type (new, update, destroy)
	Type TrafficEventType `protobuf:"varint,1,opt,name=type,proto3,enum=containarium.v1.TrafficEventType" json:"type,omitempty"`
	// The connection affected
	Connection *Connection `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// When the event occurred
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficEvent) Reset() {
	*x = TrafficEvent{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficEvent) ProtoMessage() {}

func (x *TrafficEvent) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficEvent.ProtoReflect.Descriptor instead.
func (*TrafficEvent) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficEvent) GetType() TrafficEventType {
	if x != nil {
		return x.Type
	}
	return TrafficEventType_TRAFFIC_EVENT_TYPE_UNSPECIFIED
}

func (x *TrafficEvent) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *TrafficEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ConnectionSummary provides aggregate statistics for a container
type ConnectionSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container name
	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Total active connections
	ActiveConnections int32 `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// Active TCP connections
	TcpConnections int32 `protobuf:"varint,3,opt,name=tcp_connections,json=tcpConnections,proto3" json:"tcp_connections,omitempty"`
	// Active UDP connections
	UdpConnections int32 `protobuf:"varint,4,opt,name=udp_connections,json=udpConnections,proto3" json:"udp_connections,omitempty"`
	// Total bytes sent (all connections)
	TotalBytesSent int64 `protobuf:"varint,5,opt,name=total_bytes_sent,json=totalBytesSent,proto3" json:"total_bytes_sent,omitempty"`
	// Total bytes received (all connections)
	TotalBytesReceived int64 `protobuf:"varint,6,opt,name=total_bytes_received,json=totalBytesReceived,proto3" json:"total_bytes_received,omitempty"`
	// Top destination IPs by connection count
	TopDestinations []*DestinationStats `protobuf:"bytes,7,rep,name=top_destinations,json=topDestinations,proto3" json:"top_destinations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConnectionSummary) Reset() {
	*x = ConnectionSummary{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSummary) ProtoMessage() {}

func (x *ConnectionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionSummary.ProtoReflect.Descriptor instead.
func (*ConnectionSummary) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionSummary) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ConnectionSummary) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ConnectionSummary) GetTcpConnections() int32 {
	if x != nil {
		return x.TcpConnections
	}
	return 0
}

func (x *ConnectionSummary) GetUdpConnections() int32 {
	if x != nil {
		return x.UdpConnections
	}
	return 0
}

func (x *ConnectionSummary) GetTotalBytesSent() int64 {
	if x != nil {
		return x.TotalBytesSent
	}
	return 0
}

func (x *ConnectionSummary) GetTotalBytesReceived() int64 {
	if x != nil {
		return x.TotalBytesReceived
	}
	return 0
}

func (x *ConnectionSummary) GetTopDestinations() []*DestinationStats {
	if x != nil {
		return x.TopDestinations
	}
	return nil
}

// DestinationStats provides traffic statistics for a destination
type DestinationStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination IP address
	DestIp string `protobuf:"bytes,1,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	// Number of connections to this destination
	ConnectionCount int32 `protobuf:"varint,2,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	// Total bytes transferred to/from this destination
	BytesTotal    int64 `protobuf:"varint,3,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestinationStats) Reset() {
	*x = DestinationStats{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestinationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationStats) ProtoMessage() {}

func (x *DestinationStats) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationStats.ProtoReflect.Descriptor instead.
func (*DestinationStats) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{3}
}

func (x *DestinationStats) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *DestinationStats) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *DestinationStats) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

// HistoricalConnection represents a persisted connection record
type HistoricalConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Database ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Container name
	ContainerName string `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Protocol
	Protocol Protocol `protobuf:"varint,3,opt,name=protocol,proto3,enum=containarium.v1.Protocol" json:"protocol,omitempty"`
	// Source IP address
	SourceIp string `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// Source port
	SourcePort uint32 `protobuf:"varint,5,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// Destination IP address
	DestIp string `protobuf:"bytes,6,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	// Destination port
	DestPort uint32 `protobuf:"varint,7,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	// Direction relative to container
	Direction TrafficDirection `protobuf:"varint,8,opt,name=direction,proto3,enum=containarium.v1.TrafficDirection" json:"direction,omitempty"`
	// Total bytes sent
	BytesSent int64 `protobuf:"varint,9,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	// Total bytes received
	BytesReceived int64 `protobuf:"varint,10,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	// Connection start time
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Connection end time (null if still active)
	EndedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	// Duration in seconds
	DurationSeconds int64 `protobuf:"varint,13,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HistoricalConnection) Reset() {
	*x = HistoricalConnection{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalConnection) ProtoMessage() {}

func (x *HistoricalConnection) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalConnection.ProtoReflect.Descriptor instead.
func (*HistoricalConnection) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{4}
}

func (x *HistoricalConnection) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HistoricalConnection) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *HistoricalConnection) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *HistoricalConnection) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *HistoricalConnection) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *HistoricalConnection) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *HistoricalConnection) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *HistoricalConnection) GetDirection() TrafficDirection {
	if x != nil {
		return x.Direction
	}
	return TrafficDirection_TRAFFIC_DIRECTION_UNSPECIFIED
}

func (x *HistoricalConnection) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *HistoricalConnection) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *HistoricalConnection) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *HistoricalConnection) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *HistoricalConnection) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// TrafficAggregate provides time-series aggregated traffic data
type TrafficAggregate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the aggregation interval
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Destination IP (if grouped by dest_ip)
	DestIp string `protobuf:"bytes,2,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	// Destination port (if grouped by dest_port)
	DestPort uint32 `protobuf:"varint,3,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	// Total bytes sent in this interval
	BytesSent int64 `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	// Total bytes received in this interval
	BytesReceived int64 `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	// Number of connections in this interval
	ConnectionCount int32 `protobuf:"varint,6,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrafficAggregate) Reset() {
	*x = TrafficAggregate{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficAggregate) ProtoMessage() {}

func (x *TrafficAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficAggregate.ProtoReflect.Descriptor instead.
func (*TrafficAggregate) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{5}
}

func (x *TrafficAggregate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TrafficAggregate) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *TrafficAggregate) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *TrafficAggregate) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *TrafficAggregate) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *TrafficAggregate) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

// GetConnectionsRequest retrieves active connections for a container
type GetConnectionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container name (required)
	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Filter by protocol (optional)
	Protocol Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=containarium.v1.Protocol" json:"protocol,omitempty"`
	// Filter by destination IP prefix (optional, e.g., "10.100.")
	DestIpPrefix string `protobuf:"bytes,3,opt,name=dest_ip_prefix,json=destIpPrefix,proto3" json:"dest_ip_prefix,omitempty"`
	// Filter by destination port (optional, 0 = all)
	DestPort uint32 `protobuf:"varint,4,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	// Maximum number of connections to return (default: 100)
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionsRequest) Reset() {
	*x = GetConnectionsRequest{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionsRequest) ProtoMessage() {}

func (x *GetConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionsRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{6}
}

func (x *GetConnectionsRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *GetConnectionsRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *GetConnectionsRequest) GetDestIpPrefix() string {
	if x != nil {
		return x.DestIpPrefix
	}
	return ""
}

func (x *GetConnectionsRequest) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *GetConnectionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetConnectionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Active connections
	Connections []*Connection `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	// Total count (may be more than returned if limit applied)
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionsResponse) Reset() {
	*x = GetConnectionsResponse{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionsResponse) ProtoMessage() {}

func (x *GetConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionsResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{7}
}

func (x *GetConnectionsResponse) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *GetConnectionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetConnectionSummaryRequest retrieves aggregate connection statistics
type GetConnectionSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container name (required)
	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionSummaryRequest) Reset() {
	*x = GetConnectionSummaryRequest{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionSummaryRequest) ProtoMessage() {}

func (x *GetConnectionSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionSummaryRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{8}
}

func (x *GetConnectionSummaryRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type GetConnectionSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection summary
	Summary       *ConnectionSummary `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionSummaryResponse) Reset() {
	*x = GetConnectionSummaryResponse{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionSummaryResponse) ProtoMessage() {}

func (x *GetConnectionSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionSummaryResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{9}
}

func (x *GetConnectionSummaryResponse) GetSummary() *ConnectionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// SubscribeTrafficRequest configures real-time traffic event subscription
type SubscribeTrafficRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container name (optional, empty = all containers)
	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Event types to include (empty = all types)
	EventTypes []TrafficEventType `protobuf:"varint,2,rep,packed,name=event_types,json=eventTypes,proto3,enum=containarium.v1.TrafficEventType" json:"event_types,omitempty"`
	// Only include external traffic (exclude inter-container)
	ExternalOnly  bool `protobuf:"varint,3,opt,name=external_only,json=externalOnly,proto3" json:"external_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTrafficRequest) Reset() {
	*x = SubscribeTrafficRequest{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTrafficRequest) ProtoMessage() {}

func (x *SubscribeTrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTrafficRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTrafficRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeTrafficRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *SubscribeTrafficRequest) GetEventTypes() []TrafficEventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *SubscribeTrafficRequest) GetExternalOnly() bool {
	if x != nil {
		return x.ExternalOnly
	}
	return false
}

// QueryTrafficHistoryRequest queries persisted traffic data
type QueryTrafficHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container name (required)
	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Start time for query range
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End time for query range
	EndTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Filter by destination IP (optional)
	DestIp string `protobuf:"bytes,4,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	// Filter by destination port (optional, 0 = all)
	DestPort uint32 `protobuf:"varint,5,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	// Pagination: offset
	Offset int32 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	// Pagination: limit (default: 100, max: 1000)
	Limit         int32 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTrafficHistoryRequest) Reset() {
	*x = QueryTrafficHistoryRequest{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTrafficHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTrafficHistoryRequest) ProtoMessage() {}

func (x *QueryTrafficHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTrafficHistoryRequest.ProtoReflect.Descriptor instead.
func (*QueryTrafficHistoryRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{11}
}

func (x *QueryTrafficHistoryRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *QueryTrafficHistoryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryTrafficHistoryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryTrafficHistoryRequest) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *QueryTrafficHistoryRequest) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *QueryTrafficHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryTrafficHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryTrafficHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Historical connections
	Connections []*HistoricalConnection `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	// Total count matching query
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTrafficHistoryResponse) Reset() {
	*x = QueryTrafficHistoryResponse{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTrafficHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTrafficHistoryResponse) ProtoMessage() {}

func (x *QueryTrafficHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTrafficHistoryResponse.ProtoReflect.Descriptor instead.
func (*QueryTrafficHistoryResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{12}
}

func (x *QueryTrafficHistoryResponse) GetConnections() []*HistoricalConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *QueryTrafficHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetTrafficAggregatesRequest retrieves time-series traffic aggregates
type GetTrafficAggregatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container name (required)
	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Start time
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End time
	EndTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Aggregation interval (e.g., "1m", "5m", "1h", "1d")
	Interval string `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	// Group by destination IP
	GroupByDestIp bool `protobuf:"varint,5,opt,name=group_by_dest_ip,json=groupByDestIp,proto3" json:"group_by_dest_ip,omitempty"`
	// Group by destination port
	GroupByDestPort bool `protobuf:"varint,6,opt,name=group_by_dest_port,json=groupByDestPort,proto3" json:"group_by_dest_port,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTrafficAggregatesRequest) Reset() {
	*x = GetTrafficAggregatesRequest{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrafficAggregatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrafficAggregatesRequest) ProtoMessage() {}

func (x *GetTrafficAggregatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrafficAggregatesRequest.ProtoReflect.Descriptor instead.
func (*GetTrafficAggregatesRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{13}
}

func (x *GetTrafficAggregatesRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *GetTrafficAggregatesRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetTrafficAggregatesRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetTrafficAggregatesRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *GetTrafficAggregatesRequest) GetGroupByDestIp() bool {
	if x != nil {
		return x.GroupByDestIp
	}
	return false
}

func (x *GetTrafficAggregatesRequest) GetGroupByDestPort() bool {
	if x != nil {
		return x.GroupByDestPort
	}
	return false
}

type GetTrafficAggregatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregated traffic data
	Aggregates    []*TrafficAggregate `protobuf:"bytes,1,rep,name=aggregates,proto3" json:"aggregates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrafficAggregatesResponse) Reset() {
	*x = GetTrafficAggregatesResponse{}
	mi := &file_containarium_v1_traffic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrafficAggregatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrafficAggregatesResponse) ProtoMessage() {}

func (x *GetTrafficAggregatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_traffic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrafficAggregatesResponse.ProtoReflect.Descriptor instead.
func (*GetTrafficAggregatesResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_traffic_proto_rawDescGZIP(), []int{14}
}

func (x *GetTrafficAggregatesResponse) GetAggregates() []*TrafficAggregate {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

var File_containarium_v1_traffic_proto protoreflect.FileDescriptor

const file_containarium_v1_traffic_proto_rawDesc = "" +
	"\n" +
	"\x1dcontainarium/v1/traffic.proto\x12\x0fcontainarium.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xbb\x05\n" +
	"\n" +
	"Connection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12!\n" +
	"\fcontainer_ip\x18\x03 \x01(\tR\vcontainerIp\x125\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x19.containarium.v1.ProtocolR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\x05 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x06 \x01(\rR\n" +
	"sourcePort\x12\x17\n" +
	"\adest_ip\x18\a \x01(\tR\x06destIp\x12\x1b\n" +
	"\tdest_port\x18\b \x01(\rR\bdestPort\x126\n" +
	"\x05state\x18\t \x01(\x0e2 .containarium.v1.ConnectionStateR\x05state\x12?\n" +
	"\tdirection\x18\n" +
	" \x01(\x0e2!.containarium.v1.TrafficDirectionR\tdirection\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\v \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\f \x01(\x03R\rbytesReceived\x12!\n" +
	"\fpackets_sent\x18\r \x01(\x03R\vpacketsSent\x12)\n" +
	"\x10packets_received\x18\x0e \x01(\x03R\x0fpacketsReceived\x129\n" +
	"\n" +
	"first_seen\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12'\n" +
	"\x0ftimeout_seconds\x18\x11 \x01(\x05R\x0etimeoutSeconds\"\xbc\x01\n" +
	"\fTrafficEvent\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.containarium.v1.TrafficEventTypeR\x04type\x12;\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2\x1b.containarium.v1.ConnectionR\n" +
	"connection\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe5\x02\n" +
	"\x11ConnectionSummary\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12'\n" +
	"\x0ftcp_connections\x18\x03 \x01(\x05R\x0etcpConnections\x12'\n" +
	"\x0fudp_connections\x18\x04 \x01(\x05R\x0eudpConnections\x12(\n" +
	"\x10total_bytes_sent\x18\x05 \x01(\x03R\x0etotalBytesSent\x120\n" +
	"\x14total_bytes_received\x18\x06 \x01(\x03R\x12totalBytesReceived\x12L\n" +
	"\x10top_destinations\x18\a \x03(\v2!.containarium.v1.DestinationStatsR\x0ftopDestinations\"w\n" +
	"\x10DestinationStats\x12\x17\n" +
	"\adest_ip\x18\x01 \x01(\tR\x06destIp\x12)\n" +
	"\x10connection_count\x18\x02 \x01(\x05R\x0fconnectionCount\x12\x1f\n" +
	"\vbytes_total\x18\x03 \x01(\x03R\n" +
	"bytesTotal\"\x9c\x04\n" +
	"\x14HistoricalConnection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x125\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x19.containarium.v1.ProtocolR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\x04 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x05 \x01(\rR\n" +
	"sourcePort\x12\x17\n" +
	"\adest_ip\x18\x06 \x01(\tR\x06destIp\x12\x1b\n" +
	"\tdest_port\x18\a \x01(\rR\bdestPort\x12?\n" +
	"\tdirection\x18\b \x01(\x0e2!.containarium.v1.TrafficDirectionR\tdirection\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\t \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\n" +
	" \x01(\x03R\rbytesReceived\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12)\n" +
	"\x10duration_seconds\x18\r \x01(\x03R\x0fdurationSeconds\"\xf3\x01\n" +
	"\x10TrafficAggregate\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\adest_ip\x18\x02 \x01(\tR\x06destIp\x12\x1b\n" +
	"\tdest_port\x18\x03 \x01(\rR\bdestPort\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x03R\rbytesReceived\x12)\n" +
	"\x10connection_count\x18\x06 \x01(\x05R\x0fconnectionCount\"\xce\x01\n" +
	"\x15GetConnectionsRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x125\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x19.containarium.v1.ProtocolR\bprotocol\x12$\n" +
	"\x0edest_ip_prefix\x18\x03 \x01(\tR\fdestIpPrefix\x12\x1b\n" +
	"\tdest_port\x18\x04 \x01(\rR\bdestPort\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"x\n" +
	"\x16GetConnectionsResponse\x12=\n" +
	"\vconnections\x18\x01 \x03(\v2\x1b.containarium.v1.ConnectionR\vconnections\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"D\n" +
	"\x1bGetConnectionSummaryRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\"\\\n" +
	"\x1cGetConnectionSummaryResponse\x12<\n" +
	"\asummary\x18\x01 \x01(\v2\".containarium.v1.ConnectionSummaryR\asummary\"\xa9\x01\n" +
	"\x17SubscribeTrafficRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12B\n" +
	"\vevent_types\x18\x02 \x03(\x0e2!.containarium.v1.TrafficEventTypeR\n" +
	"eventTypes\x12#\n" +
	"\rexternal_only\x18\x03 \x01(\bR\fexternalOnly\"\x99\x02\n" +
	"\x1aQueryTrafficHistoryRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x17\n" +
	"\adest_ip\x18\x04 \x01(\tR\x06destIp\x12\x1b\n" +
	"\tdest_port\x18\x05 \x01(\rR\bdestPort\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\"\x87\x01\n" +
	"\x1bQueryTrafficHistoryResponse\x12G\n" +
	"\vconnections\x18\x01 \x03(\v2%.containarium.v1.HistoricalConnectionR\vconnections\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa8\x02\n" +
	"\x1bGetTrafficAggregatesRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\tR\binterval\x12'\n" +
	"\x10group_by_dest_ip\x18\x05 \x01(\bR\rgroupByDestIp\x12+\n" +
	"\x12group_by_dest_port\x18\x06 \x01(\bR\x0fgroupByDestPort\"a\n" +
	"\x1cGetTrafficAggregatesResponse\x12A\n" +
	"\n" +
	"aggregates\x18\x01 \x03(\v2!.containarium.v1.TrafficAggregateR\n" +
	"aggregates*[\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x02\x12\x11\n" +
	"\rPROTOCOL_ICMP\x10\x03*\xc8\x02\n" +
	"\x0fConnectionState\x12 \n" +
	"\x1cCONNECTION_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CONNECTION_STATE_NEW\x10\x01\x12 \n" +
	"\x1cCONNECTION_STATE_ESTABLISHED\x10\x02\x12\x1c\n" +
	"\x18CONNECTION_STATE_RELATED\x10\x03\x12\x1e\n" +
	"\x1aCONNECTION_STATE_TIME_WAIT\x10\x04\x12\x1f\n" +
	"\x1bCONNECTION_STATE_CLOSE_WAIT\x10\x05\x12\x1d\n" +
	"\x19CONNECTION_STATE_FIN_WAIT\x10\x06\x12\x1b\n" +
	"\x17CONNECTION_STATE_CLOSED\x10\a\x12\x1d\n" +
	"\x19CONNECTION_STATE_SYN_SENT\x10\b\x12\x1d\n" +
	"\x19CONNECTION_STATE_SYN_RECV\x10\t*r\n" +
	"\x10TrafficDirection\x12!\n" +
	"\x1dTRAFFIC_DIRECTION_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TRAFFIC_DIRECTION_INGRESS\x10\x01\x12\x1c\n" +
	"\x18TRAFFIC_DIRECTION_EGRESS\x10\x02*\x91\x01\n" +
	"\x10TrafficEventType\x12\"\n" +
	"\x1eTRAFFIC_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRAFFIC_EVENT_TYPE_NEW\x10\x01\x12\x1d\n" +
	"\x19TRAFFIC_EVENT_TYPE_UPDATE\x10\x02\x12\x1e\n" +
	"\x1aTRAFFIC_EVENT_TYPE_DESTROY\x10\x032\xba\n" +
	"\n" +
	"\x0eTrafficService\x12\x85\x02\n" +
	"\x0eGetConnections\x12&.containarium.v1.GetConnectionsRequest\x1a'.containarium.v1.GetConnectionsResponse\"\xa1\x01\x92Ak\n" +
	"\aTraffic\x12\x16Get active connections\x1aHReturns active network connections for a container tracked by conntrack.\x82\xd3\xe4\x93\x02-\x12+/v1/containers/{container_name}/connections\x12\x8f\x02\n" +
	"\x14GetConnectionSummary\x12,.containarium.v1.GetConnectionSummaryRequest\x1a-.containarium.v1.GetConnectionSummaryResponse\"\x99\x01\x92A[\n" +
	"\aTraffic\x12\x16Get connection summary\x1a8Returns aggregate connection statistics for a container.\x82\xd3\xe4\x93\x025\x123/v1/containers/{container_name}/connections/summary\x12\xea\x01\n" +
	"\x10SubscribeTraffic\x12(.containarium.v1.SubscribeTrafficRequest\x1a\x1d.containarium.v1.TrafficEvent\"\x8a\x01\x92Aj\n" +
	"\aTraffic\x12\x1bSubscribe to traffic events\x1aBOpens a Server-Sent Events stream for real-time connection events.\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/traffic/subscribe0\x01\x12\x8a\x02\n" +
	"\x13QueryTrafficHistory\x12+.containarium.v1.QueryTrafficHistoryRequest\x1a,.containarium.v1.QueryTrafficHistoryResponse\"\x97\x01\x92A]\n" +
	"\aTraffic\x12\x15Query traffic history\x1a;Returns historical connection data from persistent storage.\x82\xd3\xe4\x93\x021\x12//v1/containers/{container_name}/traffic/history\x12\x93\x02\n" +
	"\x14GetTrafficAggregates\x12,.containarium.v1.GetTrafficAggregatesRequest\x1a-.containarium.v1.GetTrafficAggregatesResponse\"\x9d\x01\x92A`\n" +
	"\aTraffic\x12\x16Get traffic aggregates\x1a=Returns aggregated traffic statistics over time for analysis.\x82\xd3\xe4\x93\x024\x122/v1/containers/{container_name}/traffic/aggregatesBKZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var (
	file_containarium_v1_traffic_proto_rawDescOnce sync.Once
	file_containarium_v1_traffic_proto_rawDescData []byte
)

func file_containarium_v1_traffic_proto_rawDescGZIP() []byte {
	file_containarium_v1_traffic_proto_rawDescOnce.Do(func() {
		file_containarium_v1_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containarium_v1_traffic_proto_rawDesc), len(file_containarium_v1_traffic_proto_rawDesc)))
	})
	return file_containarium_v1_traffic_proto_rawDescData
}

var file_containarium_v1_traffic_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_containarium_v1_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_containarium_v1_traffic_proto_goTypes = []any{
	(Protocol)(0),                        // 0: containarium.v1.Protocol
	(ConnectionState)(0),                 // 1: containarium.v1.ConnectionState
	(TrafficDirection)(0),                // 2: containarium.v1.TrafficDirection
	(TrafficEventType)(0),                // 3: containarium.v1.TrafficEventType
	(*Connection)(nil),                   // 4: containarium.v1.Connection
	(*TrafficEvent)(nil),                 // 5: containarium.v1.TrafficEvent
	(*ConnectionSummary)(nil),            // 6: containarium.v1.ConnectionSummary
	(*DestinationStats)(nil),             // 7: containarium.v1.DestinationStats
	(*HistoricalConnection)(nil),         // 8: containarium.v1.HistoricalConnection
	(*TrafficAggregate)(nil),             // 9: containarium.v1.TrafficAggregate
	(*GetConnectionsRequest)(nil),        // 10: containarium.v1.GetConnectionsRequest
	(*GetConnectionsResponse)(nil),       // 11: containarium.v1.GetConnectionsResponse
	(*GetConnectionSummaryRequest)(nil),  // 12: containarium.v1.GetConnectionSummaryRequest
	(*GetConnectionSummaryResponse)(nil), // 13: containarium.v1.GetConnectionSummaryResponse
	(*SubscribeTrafficRequest)(nil),      // 14: containarium.v1.SubscribeTrafficRequest
	(*QueryTrafficHistoryRequest)(nil),   // 15: containarium.v1.QueryTrafficHistoryRequest
	(*QueryTrafficHistoryResponse)(nil),  // 16: containarium.v1.QueryTrafficHistoryResponse
	(*GetTrafficAggregatesRequest)(nil),  // 17: containarium.v1.GetTrafficAggregatesRequest
	(*GetTrafficAggregatesResponse)(nil), // 18: containarium.v1.GetTrafficAggregatesResponse
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
}
var file_containarium_v1_traffic_proto_depIdxs = []int32{
	0,  // 0: containarium.v1.Connection.protocol:type_name -> containarium.v1.Protocol
	1,  // 1: containarium.v1.Connection.state:type_name -> containarium.v1.ConnectionState
	2,  // 2: containarium.v1.Connection.direction:type_name -> containarium.v1.TrafficDirection
	19, // 3: containarium.v1.Connection.first_seen:type_name -> google.protobuf.Timestamp
	19, // 4: containarium.v1.Connection.last_seen:type_name -> google.protobuf.Timestamp
	3,  // 5: containarium.v1.TrafficEvent.type:type_name -> containarium.v1.TrafficEventType
	4,  // 6: containarium.v1.TrafficEvent.connection:type_name -> containarium.v1.Connection
	19, // 7: containarium.v1.TrafficEvent.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 8: containarium.v1.ConnectionSummary.top_destinations:type_name -> containarium.v1.DestinationStats
	0,  // 9: containarium.v1.HistoricalConnection.protocol:type_name -> containarium.v1.Protocol
	2,  // 10: containarium.v1.HistoricalConnection.direction:type_name -> containarium.v1.TrafficDirection
	19, // 11: containarium.v1.HistoricalConnection.started_at:type_name -> google.protobuf.Timestamp
	19, // 12: containarium.v1.HistoricalConnection.ended_at:type_name -> google.protobuf.Timestamp
	19, // 13: containarium.v1.TrafficAggregate.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 14: containarium.v1.GetConnectionsRequest.protocol:type_name -> containarium.v1.Protocol
	4,  // 15: containarium.v1.GetConnectionsResponse.connections:type_name -> containarium.v1.Connection
	6,  // 16: containarium.v1.GetConnectionSummaryResponse.summary:type_name -> containarium.v1.ConnectionSummary
	3,  // 17: containarium.v1.SubscribeTrafficRequest.event_types:type_name -> containarium.v1.TrafficEventType
	19, // 18: containarium.v1.QueryTrafficHistoryRequest.start_time:type_name -> google.protobuf.Timestamp
	19, // 19: containarium.v1.QueryTrafficHistoryRequest.end_time:type_name -> google.protobuf.Timestamp
	8,  // 20: containarium.v1.QueryTrafficHistoryResponse.connections:type_name -> containarium.v1.HistoricalConnection
	19, // 21: containarium.v1.GetTrafficAggregatesRequest.start_time:type_name -> google.protobuf.Timestamp
	19, // 22: containarium.v1.GetTrafficAggregatesRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 23: containarium.v1.GetTrafficAggregatesResponse.aggregates:type_name -> containarium.v1.TrafficAggregate
	10, // 24: containarium.v1.TrafficService.GetConnections:input_type -> containarium.v1.GetConnectionsRequest
	12, // 25: containarium.v1.TrafficService.GetConnectionSummary:input_type -> containarium.v1.GetConnectionSummaryRequest
	14, // 26: containarium.v1.TrafficService.SubscribeTraffic:input_type -> containarium.v1.SubscribeTrafficRequest
	15, // 27: containarium.v1.TrafficService.QueryTrafficHistory:input_type -> containarium.v1.QueryTrafficHistoryRequest
	17, // 28: containarium.v1.TrafficService.GetTrafficAggregates:input_type -> containarium.v1.GetTrafficAggregatesRequest
	11, // 29: containarium.v1.TrafficService.GetConnections:output_type -> containarium.v1.GetConnectionsResponse
	13, // 30: containarium.v1.TrafficService.GetConnectionSummary:output_type -> containarium.v1.GetConnectionSummaryResponse
	5,  // 31: containarium.v1.TrafficService.SubscribeTraffic:output_type -> containarium.v1.TrafficEvent
	16, // 32: containarium.v1.TrafficService.QueryTrafficHistory:output_type -> containarium.v1.QueryTrafficHistoryResponse
	18, // 33: containarium.v1.TrafficService.GetTrafficAggregates:output_type -> containarium.v1.GetTrafficAggregatesResponse
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_containarium_v1_traffic_proto_init() }
func file_containarium_v1_traffic_proto_init() {
	if File_containarium_v1_traffic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_traffic_proto_rawDesc), len(file_containarium_v1_traffic_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containarium_v1_traffic_proto_goTypes,
		DependencyIndexes: file_containarium_v1_traffic_proto_depIdxs,
		EnumInfos:         file_containarium_v1_traffic_proto_enumTypes,
		MessageInfos:      file_containarium_v1_traffic_proto_msgTypes,
	}.Build()
	File_containarium_v1_traffic_proto = out.File
	file_containarium_v1_traffic_proto_goTypes = nil
	file_containarium_v1_traffic_proto_depIdxs = nil
}
