apiVersion: v1
kind: Secret
metadata:
  name: {{ include "containarium-k8s.fullname" . }}-daemon
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containarium-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.daemon.jwtSecret | quote }}
