apiVersion: v1
kind: Service
metadata:
  name: {{ include "containarium-k8s.fullname" . }}-daemon
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containarium-k8s.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.daemon.service.type }}
  selector:
    {{- include "containarium-k8s.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.daemon.service.port }}
      targetPort: api
      protocol: TCP
