apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "containarium-k8s.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containarium-k8s.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "containarium-k8s.sshpiperServiceAccountName" . }}
  namespace: {{ .Values.gateway.namespace }}
  labels:
    {{- include "containarium-k8s.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
